## Link Prediction Motivation

If we can predict **whether two artists will collaborate**, we can then ask:

- What **track-level features** explain or enable that collaboration?
- What **types of collaborations** tend to increase artist popularity?

---

## Prediction Flow

```text
Predict Links 
     |
     |-- No  → Why does a collaboration NOT occur?
     |
     |-- Yes
           |
           v
     Predict Track [WE ARE HERE!!]
           |
           v
     Track Popularity
           |
           v
Track Popularity − Avg(Track Popularity)

### Read in the data

## Model

**p(track_features | artistA, artistB, graph context, objective)**

### Inputs

- **Artist embeddings**
  - node2vec / graph-based embeddings
  - learned from the collaboration graph


- **Artist A...N track_features**
  - High-level track features for each artists tracks only by themselves
  - High-level track features for each artists collaborative tracks

- **Pairwise graph features**
  - hop distance  
  - shared neighbors  
  - centrality deltas (degree, betweenness, etc.)

- **Optional historical collaboration features**
  - prior collaboration count  
  - past track performance statistics  
  - time since last collaboration  
data
  
- **Optimization / objective vector**
  - e.g. *maximize popularity*, *lean electronic*, *high energy*
  - continuous or multi-hot preference encoding

### Output

- **Distribution over track features**
  - genre probabilities  
  - tempo  
  - energy  
  - acousticness  
  - danceability  
  - valence  

---


## Conditional Variational Autoencoder (CVAE) — *Best Baseline*

### Encoder

- **Inputs**
  - track_features  
  - artist_pair_features  

- **Mapping**
  - *(track_features, artist_pair_features) → latent variable z*  
  - **q(z | track_features, artist_pair_features)**

### Decoder

- **Inputs**
  - latent variable z  
  - artist_pair_features  
  - objective_vector  

- **Mapping**
  - *(z, artist_pair_features, objective_vector) → reconstructed track_features*  
  - **p(track_features | z, artist_pair_features, objective_vector)**

### Notes

- *z* captures latent stylistic and musical factors  
- artist_pair_features condition both encoder and decoder  
- objective_vector steers generation toward desired outcomes


### Modeling Considerations

- **Track features are continuous and/or probabilistic**
  - outputs should be parameterized distributions (e.g., Gaussian, Beta, or mixtures)
  - avoid deterministic point estimates

- **Multiple valid “songs” per artist pair**
  - the mapping from artist pairs to tracks is one-to-many
  - latent variable *z* enables sampling diverse outcomes

- **Diversity + controllability**
  - diversity achieved via sampling from *z*
  - controllability achieved via conditioning on the objective_vector
  - supports exploration vs. exploitation trade-offs

#### Load / Transform the data

In [1]:
artists_feature_groups = {
    # ======================================================================================----------------------
    # Global embedding geometry (weak prior)
    # ======================================================================================----------------------
    "geometry": [
        "cos_sim_src_dst",
        "l2_dist_src_dst",
        "dot_src_dst",
        "abs_diff_mean",
        "abs_diff_max",
    ],

    # ======================================================================================----------------------
    # Popularity priors (weak but stable)
    # ======================================================================================----------------------
    "popularity": [
        "popularity_src",
        "popularity_dst",
    ],

    # ======================================================================================----------------------
    # One-hop reachability proxies (CORE SIGNAL)
    # ======================================================================================----------------------
    "one_hop": [
        # src → dst
        "max_cos_srcnbr_dst",
        "mean_cos_srcnbr_dst",
        "mean_topk_cos_srcnbr_dst",
        "num_src_neighbors",

        # dst → src
        "max_cos_dstnbr_src",
        "mean_cos_dstnbr_src",
        "mean_topk_cos_dstnbr_src",
        "num_dst_neighbors",
    ],

    # ======================================================================================----------------------
    # Two-hop graph structure (VERY STRONG SIGNAL)
    # ======================================================================================----------------------
    "two_hop": [
        "shared_neighbors",
        "jaccard_neighbors",
        "adamic_adar",
        "preferential_attachment",
    ],
}

In [2]:
import psycopg2
import pandas as pd

def audio_features_join_artist_collab(
    conn: psycopg2.extensions.connection,
    features_table_name: str
) -> pd.DataFrame:
    """
    Returns production-ready, track-level feature data joined to artist collaborations.

    Parameters
    ----------
    features_table_name : str
        One of:
        - high_level_track_audio_features
        - blocked_high_level_audio_features
        - low_level_track_audio_features
        - blocked_low_level_audio_features
    """

    allowed_tables = {
        "high_level_track_audio_features",
        "blocked_high_level_audio_features",
        "low_level_track_audio_features",
        "blocked_low_level_audio_features",
    }

    if features_table_name not in allowed_tables:
        raise ValueError(f"Invalid features table: {features_table_name}")

    q = f"""
    WITH acfl AS (
        SELECT
            a1.gid AS src_artist_gid,
            a2.gid AS dst_artist_gid,
            r.gid  AS recording_gid
        FROM artist_collab ac
        JOIN artist a1 ON a1.id = ac.artist_id
        JOIN artist a2 ON a2.id = ac.neighbor_artist_id
        JOIN recording r ON r.id = ac.recording_id
    )
    SELECT
        acfl.src_artist_gid src,
        acfl.dst_artist_gid dst,
        acfl.recording_gid,
        af.*
    FROM acfl
    JOIN {features_table_name} af
      ON af.recording_gid = acfl.recording_gid;
    """

    return pd.read_sql_query(q, con=conn)

In [3]:
import psycopg2

DB_URL = "postgres://postgres:baseball162162@localhost:5432/musicbrainz_db?sslmode=disable"

def get_pg_conn():
    """
    Returns a new Postgres connection.
    Caller is responsible for closing it.
    """
    return psycopg2.connect(DB_URL)

## Run T/L
run `transform_pipelines.ipynb` file to get artist embeddings
make sure `Extract_Transform_Audio_Features.ipynb` to get track features

In [4]:
ARTIST_EMBEDDINGS_X = './artist_embeddings_collab_neg.csv'

In [5]:
artist_embeddings = pd.read_csv(ARTIST_EMBEDDINGS_X)

conn = get_pg_conn()
# Start with just the block features for now
block_track_features = audio_features_join_artist_collab(conn,"high_level_track_audio_features")
conn.close()

/tmp/ipykernel_5429/4173504585.py:52: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(q, con=conn)

In [6]:
artist_embeddings.head(2)

,Unnamed: 0,cos_sim_src_dst,l2_dist_src_dst,dot_src_dst,abs_diff_mean,abs_diff_max,popularity_src,popularity_dst,max_cos_srcnbr_dst,mean_cos_srcnbr_dst,...,mean_cos_dstnbr_src,mean_topk_cos_dstnbr_src,num_dst_neighbors,shared_neighbors,jaccard_neighbors,adamic_adar,preferential_attachment,src,dst,label
0,0,0.861371,0.526553,0.861371,0.079166,0.188922,4.3165,2.1215,0.764570,0.764570,...,0.886804,0.886804,2,0,0.00,0.000000,4,0c1f3d1a-96ce-4d1e-87e2-9b273e083ce5,31f6ecd9-4aa1-4692-80ed-94edc6a86c2f,1
1,1,0.876171,0.497652,0.876171,0.074150,0.196402,NaN,5.8313,0.732999,0.732999,...,0.676346,0.676346,1,1,0.25,0.910239,6,fc6683fc-8591-4eae-be7c-d83cb0d0f616,d576231e-c0b6-4a42-a4f4-011f06b9095c,1

In [7]:
block_track_features.head(2)

,src,dst,recording_gid,recording_id,recording_gid,danceability,gender_female,gender_male,genre_dortmund_alternative,genre_dortmund_blues,...,moods_mirex_cluster2,moods_mirex_cluster3,moods_mirex_cluster4,moods_mirex_cluster5,timbre_bright,timbre_dark,tonal_atonal_atonal,tonal_atonal_tonal,voice_instrumental_instrumental,voice_instrumental_voice
0,65226e23-4b78-45fd-b0cf-9bc0c3124e56,cc40ae57-e255-4c49-917d-3a957bc0f267,d1df8b54-5015-4a20-ba70-ff60f93b62fc,14988161,d1df8b54-5015-4a20-ba70-ff60f93b62fc,0.016394,0.124854,0.875146,7.665742e-09,9.493277e-09,...,0.084952,0.351368,0.066901,0.419188,0.520395,0.479605,0.105982,0.894018,0.99646,0.00354
1,60f063f4-0ad9-4070-9801-3cf017728c44,382f1005-e9ab-4684-afd4-0bdae4ee37f2,d2f14fbc-6116-4e43-840e-467bf0224661,319300,d2f14fbc-6116-4e43-840e-467bf0224661,0.986504,0.244005,0.755995,4.630494e-03,1.059532e-03,...,0.200363,0.252714,0.245976,0.209203,0.925718,0.074282,0.880533,0.119467,0.19300,0.80700

In [8]:
# Join the artist connection embeddings to the track features to get our full dataset
df = block_track_features.merge(artist_embeddings, on = ['src','dst'], how = 'left')

In [9]:
df.head(2)

,src,dst,recording_gid,recording_id,recording_gid,danceability,gender_female,gender_male,genre_dortmund_alternative,genre_dortmund_blues,...,num_src_neighbors,max_cos_dstnbr_src,mean_cos_dstnbr_src,mean_topk_cos_dstnbr_src,num_dst_neighbors,shared_neighbors,jaccard_neighbors,adamic_adar,preferential_attachment,label
0,65226e23-4b78-45fd-b0cf-9bc0c3124e56,cc40ae57-e255-4c49-917d-3a957bc0f267,d1df8b54-5015-4a20-ba70-ff60f93b62fc,14988161,d1df8b54-5015-4a20-ba70-ff60f93b62fc,0.016394,0.124854,0.875146,7.665742e-09,9.493277e-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,60f063f4-0ad9-4070-9801-3cf017728c44,382f1005-e9ab-4684-afd4-0bdae4ee37f2,d2f14fbc-6116-4e43-840e-467bf0224661,319300,d2f14fbc-6116-4e43-840e-467bf0224661,0.986504,0.244005,0.755995,4.630494e-03,1.059532e-03,...,0.0,0.95193,0.95193,0.95193,1.0,0.0,0.0,0.0,15.0,1.0

In [10]:
sample_size = int(round(len(df) * 0.85, 0))

df_train = df.sample(n=sample_size, axis="index", random_state=42)
df_val = df.loc[~df.index.isin(df_train.index)]

## Model Posterior Validations

# ============================
# CVAE Model
# Predict high-level track features y from conditioning context c
# Supports:
#   - continuous targets (scaled)
#   - optional binary tag targets (0/1)
# Includes:
#   - preprocessing (impute + scale)
#   - dataset + dataloaders
#   - CVAE model
#   - training loop w/ KL warmup
#   - sampling + inverse transform back to original continuous units
#
# YOU MUST SET:
#   c_cols       : list[str] conditioning feature columns
#   y_cont_cols  : list[str] continuous target columns
#   y_bin_cols   : list[str] binary target columns (or [])
#   df_train, df_val : your split dataframes containing those columns
#
# Example:
#   c_cols = [...]
#   y_cont_cols = [...]
#   y_bin_cols = []  # or [...]
#   df_train = ...
#   df_val = ...
#   model, prep = fit_cvae(df_train, df_val, c_cols, y_cont_cols, y_bin_cols)
#   y_cont_samples, y_bin_probs = generate_for_rows(model, prep, df_val.head(3), c_cols, n_samples=200)

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from torch.utils.tensorboard import SummaryWriter

# ----------------------------
# Seed
# ----------------------------
def set_seed(seed: int = 42):
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

# ----------------------------
# Preprocessing
# ----------------------------
class CVAEPreprocessor:
    """
    Fits on TRAIN ONLY:
      - conditioning: median impute + StandardScaler
      - continuous targets: median impute + StandardScaler
      - binary targets (optional): most_frequent impute, kept as 0/1
    """
    def __init__(self):
        self.c_imputer = SimpleImputer(strategy="median")
        self.c_scaler = StandardScaler()

        self.yc_imputer = SimpleImputer(strategy="median")
        self.yc_scaler = StandardScaler()

        self.yb_imputer = SimpleImputer(strategy="most_frequent")
        self.has_bin = False
        self.fitted_ = False

    def fit(self, df: pd.DataFrame, c_cols, y_cont_cols, y_bin_cols=None):
        # conditioning
        C = self.c_imputer.fit_transform(df[c_cols])
        self.c_scaler.fit(C)

        # continuous targets
        Yc = self.yc_imputer.fit_transform(df[y_cont_cols])
        self.yc_scaler.fit(Yc)

        # binary targets
        if y_bin_cols and len(y_bin_cols) > 0:
            self.yb_imputer.fit(df[y_bin_cols])
            self.has_bin = True

        self.fitted_ = True
        return self

    def transform(self, df: pd.DataFrame, c_cols, y_cont_cols, y_bin_cols=None):
        assert self.fitted_, "Call fit() first."

        C = self.c_scaler.transform(self.c_imputer.transform(df[c_cols]))
        Yc = self.yc_scaler.transform(self.yc_imputer.transform(df[y_cont_cols]))

        if y_bin_cols and len(y_bin_cols) > 0:
            Yb = self.yb_imputer.transform(df[y_bin_cols]).astype(np.float32)
        else:
            Yb = None

        return C.astype(np.float32), Yc.astype(np.float32), Yb

    def inverse_continuous(self, Yc_scaled: np.ndarray) -> np.ndarray:
        """Scaled -> original continuous units."""
        return self.yc_scaler.inverse_transform(Yc_scaled)

# ----------------------------
# Dataset
# ----------------------------
class CVAEDataset(Dataset):
    def __init__(self, C, Yc, Yb=None):
        self.C = C
        self.Yc = Yc
        self.Yb = Yb

    def __len__(self):
        return len(self.C)

    def __getitem__(self, idx):
        if self.Yb is None:
            return self.C[idx], self.Yc[idx]
        return self.C[idx], self.Yc[idx], self.Yb[idx]

# ----------------------------
# Model
# ----------------------------
class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim, dropout=0.1):
        super().__init__()
        layers = []
        d = in_dim
        for h in hidden:
            layers += [nn.Linear(d, h), nn.ReLU(), nn.Dropout(dropout)]
            d = h
        layers.append(nn.Linear(d, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

class CVAE(nn.Module):
    """
    Encoder: q(z | y_cont, c) -> mu, logvar
    Decoder: p(y_cont, y_bin | z, c)
    """
    def __init__(self, c_dim, y_cont_dim, z_dim=16, hidden=(256, 256), bin_dim=0, dropout=0.1):
        super().__init__()
        self.z_dim = z_dim
        self.c_dim = c_dim
        self.y_cont_dim = y_cont_dim
        self.bin_dim = bin_dim

        # Encoder takes [y_cont, c]
        self.encoder = MLP(
            in_dim=y_cont_dim + c_dim,
            hidden=hidden,
            out_dim=2 * z_dim,
            dropout=dropout
        )

        # Decoder takes [z, c] -> y_cont
        self.decoder_y = MLP(
            in_dim=z_dim + c_dim,
            hidden=hidden,
            out_dim=y_cont_dim,
            dropout=dropout
        )

        # Optional binary head
        self.decoder_bin = None
        if bin_dim > 0:
            self.decoder_bin = MLP(
                in_dim=z_dim + c_dim,
                hidden=hidden,
                out_dim=bin_dim,
                dropout=dropout
            )

    def encode(self, y_cont, c):
        h = torch.cat([y_cont, c], dim=1)
        params = self.encoder(h)
        mu, logvar = params[:, : self.z_dim], params[:, self.z_dim :]
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, c):
        h = torch.cat([z, c], dim=1)
        y_cont_hat = self.decoder_y(h)
        yb_logits = self.decoder_bin(h) if self.decoder_bin is not None else None
        return y_cont_hat, yb_logits

    def forward(self, y_cont, c):
        mu, logvar = self.encode(y_cont, c)
        z = self.reparameterize(mu, logvar)
        y_cont_hat, yb_logits = self.decode(z, c)
        return y_cont_hat, yb_logits, mu, logvar

# ----------------------------
# Loss
# ----------------------------
def kl_div(mu, logvar):
    # 0.5 * sum(exp(logvar) + mu^2 - 1 - logvar)
    return 0.5 * torch.sum(torch.exp(logvar) + mu**2 - 1.0 - logvar, dim=1)

def beta_schedule(epoch, warmup_epochs=10, max_beta=1.0):
    if warmup_epochs <= 0:
        return max_beta
    return max_beta * min(1.0, (epoch + 1) / warmup_epochs)

def cvae_loss(yc_hat, yc_true, mu, logvar, yb_logits=None, yb_true=None, beta=1.0, bin_weight=1.0):
    # reconstruction on scaled continuous targets
    rec_yc = F.mse_loss(yc_hat, yc_true, reduction="none").sum(dim=1)

    rec_yb = torch.zeros_like(rec_yc)
    if yb_logits is not None and yb_true is not None:
        rec_yb = F.binary_cross_entropy_with_logits(yb_logits, yb_true, reduction="none").sum(dim=1)

    kl = kl_div(mu, logvar)
    loss = rec_yc + bin_weight * rec_yb + beta * kl
    return loss.mean(), {
        "loss": float(loss.mean().detach().cpu()),
        "rec_yc": float(rec_yc.mean().detach().cpu()),
        "rec_yb": float(rec_yb.mean().detach().cpu()) if (yb_logits is not None and yb_true is not None) else 0.0,
        "kl": float(kl.mean().detach().cpu()),
        "beta": float(beta),
    }

# ----------------------------
# Train / Eval
# ----------------------------
@torch.no_grad()
def evaluate(model, loader, device, beta=1.0, bin_weight=1.0):
    model.eval()
    totals = {"loss": 0.0, "rec_yc": 0.0, "rec_yb": 0.0, "kl": 0.0}
    n = 0

    for batch in loader:
        if len(batch) == 2:
            c, yc = batch
            yb = None
        else:
            c, yc, yb = batch

        c = c.to(device)
        yc = yc.to(device)
        yb = yb.to(device) if yb is not None else None

        yc_hat, yb_logits, mu, logvar = model(yc, c)
        _, m = cvae_loss(yc_hat, yc, mu, logvar, yb_logits, yb, beta=beta, bin_weight=bin_weight)

        bs = c.size(0)
        n += bs
        for k in totals:
            totals[k] += m[k] * bs

    return {k: totals[k] / max(n, 1) for k in totals}

def train_cvae(
    model,
    train_loader,
    val_loader,
    device,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    grad_clip=5.0
):
    model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr)

    best = None
    best_state = None

    for epoch in range(epochs):
        model.train()
        beta = beta_schedule(epoch, warmup_epochs=warmup_epochs, max_beta=max_beta)

        totals = {"loss": 0.0, "rec_yc": 0.0, "rec_yb": 0.0, "kl": 0.0}
        n = 0

        for batch in train_loader:
            if len(batch) == 2:
                c, yc = batch
                yb = None
            else:
                c, yc, yb = batch

            c = c.to(device)
            yc = yc.to(device)
            yb = yb.to(device) if yb is not None else None

            opt.zero_grad(set_to_none=True)
            yc_hat, yb_logits, mu, logvar = model(yc, c)
            loss, m = cvae_loss(yc_hat, yc, mu, logvar, yb_logits, yb, beta=beta, bin_weight=bin_weight)
            loss.backward()
            if grad_clip is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            opt.step()

            bs = c.size(0)
            n += bs
            for k in totals:
                totals[k] += m[k] * bs

        train_m = {k: totals[k] / max(n, 1) for k in totals}
        val_m = evaluate(model, val_loader, device, beta=1.0, bin_weight=bin_weight) if val_loader is not None else None
        
        # ---------------------------------------
        # --- TensorBoard logging ---
        writer.add_scalar("loss/train", train_m["loss"], epoch)
        writer.add_scalar("recon/train", train_m["rec_yc"], epoch)
        writer.add_scalar("kl/train", train_m["kl"], epoch)
        writer.add_scalar("beta", beta, epoch)

        if val_m is not None:
            writer.add_scalar("loss/val", val_m["loss"], epoch)
            writer.add_scalar("recon/val", val_m["rec_yc"], epoch)
            writer.add_scalar("kl/val", val_m["kl"], epoch)

        score = val_m["loss"] if val_m is not None else train_m["loss"]
        if best is None or score < best:
            best = score
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        msg = (
            f"Epoch {epoch+1:02d}/{epochs} | "
            f"train loss {train_m['loss']:.4f} "
            f"(rec_yc {train_m['rec_yc']:.4f}, "
            f"rec_yb {train_m['rec_yb']:.4f}, "
            f"kl {train_m['kl']:.4f}, "
            f"beta {beta:.3f})"
        )
        if val_m is not None:
            msg += f" | val loss {val_m['loss']:.4f} (rec_yc {val_m['rec_yc']:.4f}, rec_yb {val_m['rec_yb']:.4f}, kl {val_m['kl']:.4f})"
        print(msg)

    if best_state is not None:
        model.load_state_dict(best_state)
    return model

# ----------------------------
# Fit helper
# ----------------------------
def fit_cvae(
    df_train: pd.DataFrame,
    df_val: pd.DataFrame,
    c_cols,
    y_cont_cols,
    y_bin_cols=None,
    *,
    z_dim=16,
    hidden=(256, 256),
    dropout=0.1,
    batch_size=512,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    num_workers=0,
    seed=42
):
    writer = SummaryWriter(log_dir="runs/cvae_tracks")
    log_dir=f"runs/cvae_tracks_z{z_dim}"
    set_seed(seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    y_bin_cols = y_bin_cols or []

    prep = CVAEPreprocessor().fit(df_train, c_cols, y_cont_cols, y_bin_cols)

    C_tr, Yc_tr, Yb_tr = prep.transform(df_train, c_cols, y_cont_cols, y_bin_cols)
    C_va, Yc_va, Yb_va = prep.transform(df_val, c_cols, y_cont_cols, y_bin_cols)

    ds_tr = CVAEDataset(C_tr, Yc_tr, Yb_tr)
    ds_va = CVAEDataset(C_va, Yc_va, Yb_va)

    train_loader = DataLoader(ds_tr, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)
    val_loader = DataLoader(ds_va, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True)

    model = CVAE(
        c_dim=len(c_cols),
        y_cont_dim=len(y_cont_cols),
        z_dim=z_dim,
        hidden=hidden,
        bin_dim=len(y_bin_cols),
        dropout=dropout
    )

    model = train_cvae(
        model,
        train_loader,
        val_loader,
        device=device,
        epochs=epochs,
        lr=lr,
        warmup_epochs=warmup_epochs,
        max_beta=max_beta,
        bin_weight=bin_weight
    )

    return model, prep

# ----------------------------
# Generation helpers
# ----------------------------
@torch.no_grad()
def generate_for_rows(model, prep, df_rows: pd.DataFrame, c_cols, *, n_samples=100, device=None):
    """
    Given df_rows with conditioning columns, generate n_samples synthetic tracks per row.
    Returns:
      y_cont_samples_original_units: shape (n_rows, n_samples, y_cont_dim)
      y_bin_probs: shape (n_rows, n_samples, y_bin_dim) or None
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    model.eval()
    model.to(device)

    # Transform conditioning only
    C = prep.c_scaler.transform(prep.c_imputer.transform(df_rows[c_cols])).astype(np.float32)

    C_t = torch.tensor(C, dtype=torch.float32, device=device)  # (n_rows, c_dim)
    n_rows = C_t.size(0)

    # Repeat each row n_samples times
    C_rep = C_t.unsqueeze(1).repeat(1, n_samples, 1).reshape(n_rows * n_samples, -1)
    z = torch.randn((n_rows * n_samples, model.z_dim), device=device)

    yc_hat_scaled, yb_logits = model.decode(z, C_rep)

    yc_hat_scaled = yc_hat_scaled.detach().cpu().numpy().reshape(n_rows, n_samples, -1)
    yc_hat = prep.inverse_continuous(yc_hat_scaled.reshape(-1, yc_hat_scaled.shape[-1])).reshape(n_rows, n_samples, -1)

    yb_probs = None
    if yb_logits is not None:
        yb_probs = torch.sigmoid(yb_logits).detach().cpu().numpy().reshape(n_rows, n_samples, -1)

    return yc_hat, yb_probs

In [11]:
# ============================
# CVAE Model 
# Predict high-level track features y from conditioning context c
# Supports:
#   - continuous targets (scaled)
#   - optional binary tag targets (0/1)
# Includes:
#   - preprocessing (impute + scale)
#   - dataset + dataloaders
#   - CVAE model
#   - training loop w/ KL warmup
#   - TensorBoard logging
#   - sampling + inverse transform back to original continuous units
#
# YOU MUST SET:
#   c_cols       : list[str] conditioning feature columns
#   y_cont_cols  : list[str] continuous target columns
#   y_bin_cols   : list[str] binary target columns (or [])
#   df_train, df_val : your split dataframes containing those columns
#
# Example:
#   c_cols = [...]
#   y_cont_cols = [...]
#   y_bin_cols = []  # or [...]
#   df_train = ...
#   df_val = ...
#   model, prep, writer = fit_cvae(df_train, df_val, c_cols, y_cont_cols, y_bin_cols, z_dim=16)
#   y_cont_samples, y_bin_probs = generate_for_rows(model, prep, df_val.head(3), c_cols, n_samples=200)
#
# Run TensorBoard:
#   tensorboard --logdir runs
#   open http://localhost:6006

import os
import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from torch.utils.tensorboard import SummaryWriter

# --- generative validation deps ---
from sklearn.metrics import pairwise_distances
from sklearn.linear_model import Ridge
from scipy.stats import pearsonr


# ----------------------------
# Seed
# ----------------------------
def set_seed(seed: int = 42):
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

# ----------------------------
# Preprocessing
# ----------------------------
class CVAEPreprocessor:
    """
    Fits on TRAIN ONLY:
      - conditioning: median impute + StandardScaler
      - continuous targets: median impute + StandardScaler
      - binary targets (optional): most_frequent impute, kept as 0/1
    """
    def __init__(self):
        self.c_imputer = SimpleImputer(strategy="median")
        self.c_scaler = StandardScaler()

        self.yc_imputer = SimpleImputer(strategy="median")
        self.yc_scaler = StandardScaler()

        self.yb_imputer = SimpleImputer(strategy="most_frequent")
        self.has_bin = False
        self.fitted_ = False

    def fit(self, df: pd.DataFrame, c_cols, y_cont_cols, y_bin_cols=None):
        # conditioning
        C = self.c_imputer.fit_transform(df[c_cols])
        self.c_scaler.fit(C)

        # continuous targets
        Yc = self.yc_imputer.fit_transform(df[y_cont_cols])
        self.yc_scaler.fit(Yc)

        # binary targets
        if y_bin_cols and len(y_bin_cols) > 0:
            self.yb_imputer.fit(df[y_bin_cols])
            self.has_bin = True

        self.fitted_ = True
        return self

    def transform(self, df: pd.DataFrame, c_cols, y_cont_cols, y_bin_cols=None):
        assert self.fitted_, "Call fit() first."

        C = self.c_scaler.transform(self.c_imputer.transform(df[c_cols]))
        Yc = self.yc_scaler.transform(self.yc_imputer.transform(df[y_cont_cols]))

        if y_bin_cols and len(y_bin_cols) > 0:
            Yb = self.yb_imputer.transform(df[y_bin_cols]).astype(np.float32)
        else:
            Yb = None

        return C.astype(np.float32), Yc.astype(np.float32), Yb

    def inverse_continuous(self, Yc_scaled: np.ndarray) -> np.ndarray:
        """Scaled -> original continuous units."""
        return self.yc_scaler.inverse_transform(Yc_scaled)

# ----------------------------
# Dataset
# ----------------------------
class CVAEDataset(Dataset):
    def __init__(self, C, Yc, Yb=None):
        self.C = C
        self.Yc = Yc
        self.Yb = Yb

    def __len__(self):
        return len(self.C)

    def __getitem__(self, idx):
        if self.Yb is None:
            return self.C[idx], self.Yc[idx]
        return self.C[idx], self.Yc[idx], self.Yb[idx]

# ----------------------------
# Model
# ----------------------------
class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim, dropout=0.1):
        super().__init__()
        layers = []
        d = in_dim
        for h in hidden:
            layers += [nn.Linear(d, h), nn.ReLU(), nn.Dropout(dropout)]
            d = h
        layers.append(nn.Linear(d, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

class CVAE(nn.Module):
    """
    Encoder: q(z | y_cont, c) -> mu, logvar
    Decoder: p(y_cont, y_bin | z, c)
    """
    def __init__(self, c_dim, y_cont_dim, z_dim=16, hidden=(256, 256), bin_dim=0, dropout=0.1):
        super().__init__()
        self.z_dim = z_dim
        self.c_dim = c_dim
        self.y_cont_dim = y_cont_dim
        self.bin_dim = bin_dim

        # Encoder takes [y_cont, c]
        self.encoder = MLP(
            in_dim=y_cont_dim + c_dim,
            hidden=hidden,
            out_dim=2 * z_dim,
            dropout=dropout
        )

        # Decoder takes [z, c] -> y_cont
        self.decoder_y = MLP(
            in_dim=z_dim + c_dim,
            hidden=hidden,
            out_dim=y_cont_dim,
            dropout=dropout
        )

        # Optional binary head
        self.decoder_bin = None
        if bin_dim > 0:
            self.decoder_bin = MLP(
                in_dim=z_dim + c_dim,
                hidden=hidden,
                out_dim=bin_dim,
                dropout=dropout
            )

    def encode(self, y_cont, c):
        h = torch.cat([y_cont, c], dim=1)
        params = self.encoder(h)
        mu, logvar = params[:, : self.z_dim], params[:, self.z_dim :]
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, c):
        h = torch.cat([z, c], dim=1)
        y_cont_hat = self.decoder_y(h)
        yb_logits = self.decoder_bin(h) if self.decoder_bin is not None else None
        return y_cont_hat, yb_logits

    def forward(self, y_cont, c):
        mu, logvar = self.encode(y_cont, c)
        z = self.reparameterize(mu, logvar)
        y_cont_hat, yb_logits = self.decode(z, c)
        return y_cont_hat, yb_logits, mu, logvar

# ----------------------------
# Loss
# ----------------------------
def kl_div(mu, logvar):
    # 0.5 * sum(exp(logvar) + mu^2 - 1 - logvar)
    return 0.5 * torch.sum(torch.exp(logvar) + mu**2 - 1.0 - logvar, dim=1)

def beta_schedule(epoch, warmup_epochs=10, max_beta=1.0):
    if warmup_epochs <= 0:
        return max_beta
    return max_beta * min(1.0, (epoch + 1) / warmup_epochs)

def cvae_loss(yc_hat, yc_true, mu, logvar, yb_logits=None, yb_true=None, beta=1.0, bin_weight=1.0):
    # reconstruction on scaled continuous targets
    rec_yc = F.mse_loss(yc_hat, yc_true, reduction="none").sum(dim=1)

    rec_yb = torch.zeros_like(rec_yc)
    if yb_logits is not None and yb_true is not None:
        rec_yb = F.binary_cross_entropy_with_logits(yb_logits, yb_true, reduction="none").sum(dim=1)

    kl = kl_div(mu, logvar)
    loss = rec_yc + bin_weight * rec_yb + beta * kl

    # Return mean + per-batch metrics
    return loss.mean(), {
        "loss": float(loss.mean().detach().cpu()),
        "rec_yc": float(rec_yc.mean().detach().cpu()),
        "rec_yb": float(rec_yb.mean().detach().cpu()) if (yb_logits is not None and yb_true is not None) else 0.0,
        "kl": float(kl.mean().detach().cpu()),
    }


# ----------------------------
# Generation helpers
# ----------------------------
@torch.no_grad()
def generate_for_rows(model, prep, df_rows: pd.DataFrame, c_cols, *, n_samples=100, device=None):
    """
    Given df_rows with conditioning columns, generate n_samples synthetic tracks per row.
    Returns:
      y_cont_samples_original_units: shape (n_rows, n_samples, y_cont_dim)
      y_bin_probs: shape (n_rows, n_samples, y_bin_dim) or None
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    model.eval()
    model.to(device)

    # Transform conditioning only
    C = prep.c_scaler.transform(prep.c_imputer.transform(df_rows[c_cols])).astype(np.float32)

    C_t = torch.tensor(C, dtype=torch.float32, device=device)  # (n_rows, c_dim)
    n_rows = C_t.size(0)

    # Repeat each row n_samples times
    C_rep = C_t.unsqueeze(1).repeat(1, n_samples, 1).reshape(n_rows * n_samples, -1)
    z = torch.randn((n_rows * n_samples, model.z_dim), device=device)

    yc_hat_scaled, yb_logits = model.decode(z, C_rep)

    yc_hat_scaled = yc_hat_scaled.detach().cpu().numpy().reshape(n_rows, n_samples, -1)
    yc_hat = prep.inverse_continuous(
        yc_hat_scaled.reshape(-1, yc_hat_scaled.shape[-1])
    ).reshape(n_rows, n_samples, -1)

    yb_probs = None
    if yb_logits is not None:
        yb_probs = torch.sigmoid(yb_logits).detach().cpu().numpy().reshape(n_rows, n_samples, -1)

    return yc_hat, yb_probs


# ///////////////////////////////////////////////////////////////////////////////////////////////////////
# ============================
# GENERATIVE VALIDATION
# Loss curves alone do NOT validate a generative model.
# This section adds:
#   1) Sample diversity metrics
#   2) Correlation vs real data
#   3) Downstream task performance (e.g. popularity ranking)
#
# These log into the SAME TensorBoard run created in fit_cvae.
# ============================

@torch.no_grad()
def log_sample_diversity_to_tb(
    writer,
    model,
    prep,
    df_eval,
    c_cols,
    epoch,
    *,
    n_rows=10,
    n_samples=100,
    device=None,
):
    """
    Sample diversity metrics
    Detects mode collapse.

    Logs:
      - gen/diversity_mean_feature_std
      - gen/diversity_mean_pairwise_dist
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    df_sub = df_eval.sample(min(n_rows, len(df_eval)))
    yc_samples, _ = generate_for_rows(model, prep, df_sub, c_cols, n_samples=n_samples, device=device)

    flat = yc_samples.reshape(-1, yc_samples.shape[-1])
    mean_std = float(flat.std(axis=0).mean())
    
    # sample at most 200 points to avoid OOM
    if flat.shape[0] > 200:
        idx = np.random.choice(flat.shape[0], 200, replace=False)
        flat = flat[idx]

    mean_pwd = float(pairwise_distances(flat).mean())
    
    writer.add_scalar("gen/diversity_mean_feature_std", mean_std, epoch)
    writer.add_scalar("gen/diversity_mean_pairwise_dist", mean_pwd, epoch)


@torch.no_grad()
def log_correlation_to_tb(
    writer,
    model,
    prep,
    df_eval,
    c_cols,
    y_cont_cols,
    epoch,
    *,
    n_samples=100,
    device=None,
):
    """
    Correlation vs real data

    For each eval row:
      - generate samples
      - compare generated mean to real track
    Logs:
      - gen/mean_abs_feature_corr
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    yc_samples, _ = generate_for_rows(model, prep, df_eval, c_cols, n_samples=n_samples, device=device)
    gen_mean = yc_samples.mean(axis=1)
    real = df_eval[y_cont_cols].values

    corrs = []
    for i in range(gen_mean.shape[1]):
        try:
            c, _ = pearsonr(gen_mean[:, i], real[:, i])
            if np.isfinite(c):
                corrs.append(abs(c))
        except Exception:
            pass

    mean_abs_corr = float(np.mean(corrs)) if corrs else 0.0
    writer.add_scalar("gen/mean_abs_feature_corr", mean_abs_corr, epoch)


def log_popularity_ranking_to_tb(
    writer,
    model,
    prep,
    df_train,
    df_eval,
    c_cols,
    y_cont_cols,
    popularity_col,
    epoch,
    *,
    n_samples=100,
    device=None,
):
    """
    Downstream task performance (e.g. popularity ranking)

    Trains a popularity regressor on REAL tracks,
    then evaluates ranking quality on GENERATED samples.

    Logs:
      - gen/popularity_rank_corr
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    if popularity_col not in df_train.columns or popularity_col not in df_eval.columns:
        # don't crash training if you haven't joined popularity yet
        writer.add_scalar("gen/popularity_rank_corr", np.nan, epoch)
        return

    pop_model = Ridge(alpha=1.0)
    pop_model.fit(df_train[y_cont_cols], df_train[popularity_col])

    yc_samples, _ = generate_for_rows(model, prep, df_eval, c_cols, n_samples=n_samples, device=device)

    n_rows = yc_samples.shape[0]
    scores = pop_model.predict(yc_samples.reshape(-1, yc_samples.shape[-1]))
    scores = scores.reshape(n_rows, n_samples)

    best_synth = scores.max(axis=1)
    real_pop = df_eval[popularity_col].values

    try:
        corr, _ = pearsonr(best_synth, real_pop)
    except Exception:
        corr = np.nan

    writer.add_scalar("gen/popularity_rank_corr", float(corr), epoch)


# ----------------------------
# Train / Eval
# ----------------------------
@torch.no_grad()
def evaluate(model, loader, device, beta=1.0, bin_weight=1.0):
    model.eval()
    totals = {"loss": 0.0, "rec_yc": 0.0, "rec_yb": 0.0, "kl": 0.0}
    n = 0

    for batch in loader:
        if len(batch) == 2:
            c, yc = batch
            yb = None
        else:
            c, yc, yb = batch

        c = c.to(device)
        yc = yc.to(device)
        yb = yb.to(device) if yb is not None else None

        yc_hat, yb_logits, mu, logvar = model(yc, c)
        _, m = cvae_loss(yc_hat, yc, mu, logvar, yb_logits, yb, beta=beta, bin_weight=bin_weight)

        bs = c.size(0)
        n += bs
        for k in totals:
            totals[k] += m[k] * bs

    return {k: totals[k] / max(n, 1) for k in totals}

def train_cvae(
    model,
    train_loader,
    val_loader,
    device,
    writer: SummaryWriter,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    grad_clip=5.0,
    log_hists_every=0,
    y_cont_cols=None,
    prep=None,
    # --- additive only: used for generative validation logging ---
    df_train=None,
    df_val=None,
    c_cols=None,
    popularity_col="track_popularity",
    gen_eval_every=5,
    gen_eval_n_samples=100,
    gen_eval_n_rows=10,
):
    """
    log_hists_every:
      - 0 disables histogram logging
      - otherwise logs generated histograms every N epochs (requires y_cont_cols + prep)
    """
    model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr)

    best = None
    best_state = None
    global_step = 0

    for epoch in range(epochs):
        model.train()
        beta = beta_schedule(epoch, warmup_epochs=warmup_epochs, max_beta=max_beta)

        totals = {"loss": 0.0, "rec_yc": 0.0, "rec_yb": 0.0, "kl": 0.0}
        n = 0

        for batch in train_loader:
            if len(batch) == 2:
                c, yc = batch # Conditional variables, y_conditionals
                yb = None     # y-bin conditional
            else:
                c, yc, yb = batch

            c = c.to(device)
            yc = yc.to(device)
            yb = yb.to(device) if yb is not None else None

            opt.zero_grad(set_to_none=True)
            yc_hat, yb_logits, mu, logvar = model(yc, c) # Predicted y_conditionals, y-bin logit predictions, error, logvariance
            loss, m = cvae_loss(yc_hat, yc, mu, logvar, yb_logits, yb, beta=beta, bin_weight=bin_weight)
            loss.backward()
            if grad_clip is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            opt.step()

            bs = c.size(0)
            n += bs
            global_step += 1

            # accumulate epoch metrics
            for k in totals:
                totals[k] += m[k] * bs

        train_m = {k: totals[k] / max(n, 1) for k in totals}
        val_m = evaluate(model, val_loader, device, beta=1.0, bin_weight=bin_weight) if val_loader is not None else None

        # ---------------------------------------
        # TensorBoard scalar logging
        # ---------------------------------------
        writer.add_scalar("loss/train", train_m["loss"], epoch)
        writer.add_scalar("recon_yc/train", train_m["rec_yc"], epoch)
        writer.add_scalar("recon_yb/train", train_m["rec_yb"], epoch)
        writer.add_scalar("kl/train", train_m["kl"], epoch)
        writer.add_scalar("beta", beta, epoch)

        if val_m is not None:
            writer.add_scalar("loss/val", val_m["loss"], epoch)
            writer.add_scalar("recon_yc/val", val_m["rec_yc"], epoch)
            writer.add_scalar("recon_yb/val", val_m["rec_yb"], epoch)
            writer.add_scalar("kl/val", val_m["kl"], epoch)

        # Optional latent stats (useful for collapse debugging)
        # We log from the last batch of the epoch (good enough)
        with torch.no_grad():
            writer.add_scalar("latent/mu_mean", float(mu.mean().detach().cpu()), epoch)
            writer.add_scalar("latent/mu_std", float(mu.std().detach().cpu()), epoch)
            writer.add_scalar("latent/logvar_mean", float(logvar.mean().detach().cpu()), epoch)

        # Optional histogram logging (off by default)
        if log_hists_every and (epoch % log_hists_every == 0) and (prep is not None) and (y_cont_cols is not None):
            # Log histograms of reconstructed yc_hat (scaled space) for a quick view of collapse/noise
            # Use last batch's yc_hat
            yc_hat_np = yc_hat.detach().cpu().numpy()
            # unscale to original units for interpretability
            yc_hat_unscaled = prep.inverse_continuous(yc_hat_np)
            for j, feat in enumerate(y_cont_cols[: min(10, len(y_cont_cols))]):
                writer.add_histogram(f"recon_unscaled/{feat}", yc_hat_unscaled[:, j], epoch)

        # --------------------------------------------------
        # GENERATIVE VALIDATION (offline checks)
        # Loss curves alone cannot validate a generative model.
        # --------------------------------------------------
        if (
            gen_eval_every
            and (epoch % gen_eval_every == 0)
            and (prep is not None)
            and (y_cont_cols is not None)
            and (df_train is not None)
            and (df_val is not None)
            and (c_cols is not None)
        ):
            log_sample_diversity_to_tb(
                writer, model, prep, df_val, c_cols, epoch,
                n_rows=gen_eval_n_rows,
                n_samples=gen_eval_n_samples,
                device=device
            )
            log_correlation_to_tb(
                writer, model, prep, df_val, c_cols, y_cont_cols, epoch,
                n_samples=gen_eval_n_samples,
                device=device
            )
            log_popularity_ranking_to_tb(
                writer, model, prep,
                df_train, df_val,
                c_cols, y_cont_cols,
                popularity_col=popularity_col,
                epoch=epoch,
                n_samples=gen_eval_n_samples,
                device=device
            )

        score = val_m["loss"] if val_m is not None else train_m["loss"]
        if best is None or score < best:
            best = score
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        msg = (
            f"Epoch {epoch+1:02d}/{epochs} | "
            f"train loss {train_m['loss']:.4f} "
            f"(rec_yc {train_m['rec_yc']:.4f}, "
            f"rec_yb {train_m['rec_yb']:.4f}, "
            f"kl {train_m['kl']:.4f}, "
            f"beta {beta:.3f})"
        )
        if val_m is not None:
            msg += (
                f" | val loss {val_m['loss']:.4f} "
                f"(rec_yc {val_m['rec_yc']:.4f}, rec_yb {val_m['rec_yb']:.4f}, kl {val_m['kl']:.4f})"
            )
        print(msg)

    if best_state is not None:
        model.load_state_dict(best_state)
    return model

# ----------------------------
# Fit helper
# ----------------------------
def fit_cvae(
    df_train: pd.DataFrame,
    df_val: pd.DataFrame,
    c_cols,
    y_cont_cols,
    y_bin_cols=None,
    *,
    z_dim=16,
    hidden=(256, 256),
    dropout=0.1,
    batch_size=512,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    num_workers=0,
    seed=42,
    log_root="runs",
    run_name=None,
    log_hists_every=0
):
    """
    Returns: (model, prep, writer)
    """
    set_seed(seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    y_bin_cols = y_bin_cols or []

    # Unique run dir
    if run_name is None:
        ts = time.strftime("%Y%m%d_%H%M%S")
        run_name = f"cvae_tracks_z{z_dim}_h{'-'.join(map(str, hidden))}_{ts}"
    log_dir = os.path.join(log_root, run_name)
    writer = SummaryWriter(log_dir=log_dir)

    # Fit preprocessors on TRAIN ONLY
    prep = CVAEPreprocessor().fit(df_train, c_cols, y_cont_cols, y_bin_cols)

    # Transform to numpy arrays
    C_tr, Yc_tr, Yb_tr = prep.transform(df_train, c_cols, y_cont_cols, y_bin_cols)
    C_va, Yc_va, Yb_va = prep.transform(df_val, c_cols, y_cont_cols, y_bin_cols)

    # Datasets / Loaders
    ds_tr = CVAEDataset(C_tr, Yc_tr, Yb_tr)
    ds_va = CVAEDataset(C_va, Yc_va, Yb_va)

    train_loader = DataLoader(ds_tr, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)
    val_loader = DataLoader(ds_va, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True)

    # Model
    model = CVAE(
        c_dim=len(c_cols),
        y_cont_dim=len(y_cont_cols),
        z_dim=z_dim,
        hidden=hidden,
        bin_dim=len(y_bin_cols),
        dropout=dropout
    )

    # Train
    model = train_cvae(
        model,
        train_loader,
        val_loader,
        device=device,
        writer=writer,
        epochs=epochs,
        lr=lr,
        warmup_epochs=warmup_epochs,
        max_beta=max_beta,
        bin_weight=bin_weight,
        log_hists_every=log_hists_every,
        y_cont_cols=y_cont_cols,
        prep=prep,
        # --- generative validation wiring ---
        df_train=df_train,
        df_val=df_val,
        c_cols=c_cols,
        popularity_col="track_popularity",
        gen_eval_every=10,
        gen_eval_n_samples=50,
        gen_eval_n_rows=5
    )

    # Optional: log model graph (can fail in some cases; safe to skip)
    # try:
    #     example_c = torch.tensor(C_tr[:2], dtype=torch.float32, device=device)
    #     example_y = torch.tensor(Yc_tr[:2], dtype=torch.float32, device=device)
    #     writer.add_graph(model, (example_y, example_c))
    # except Exception:
    #     pass

    return model, prep, writer

## Create the model

# ============================
# CVAE Model 
# Predict high-level track features y from conditioning context c
# Supports:
#   - continuous targets (scaled)
#   - optional binary tag targets (0/1)
# Includes:
#   - preprocessing (impute + scale)
#   - dataset + dataloaders
#   - CVAE model
#   - training loop w/ KL warmup
#   - TensorBoard logging
#   - sampling + inverse transform back to original continuous units
#
# YOU MUST SET:
#   c_cols       : list[str] conditioning feature columns
#   y_cont_cols  : list[str] continuous target columns
#   y_bin_cols   : list[str] binary target columns (or [])
#   df_train, df_val : your split dataframes containing those columns
#
# Example:
#   c_cols = [...]
#   y_cont_cols = [...]
#   y_bin_cols = []  # or [...]
#   df_train = ...
#   df_val = ...
#   model, prep, writer = fit_cvae(df_train, df_val, c_cols, y_cont_cols, y_bin_cols, z_dim=16)
#   y_cont_samples, y_bin_probs = generate_for_rows(model, prep, df_val.head(3), c_cols, n_samples=200)
#
# Run TensorBoard:
#   tensorboard --logdir runs
#   open http://localhost:6006

import os
import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from torch.utils.tensorboard import SummaryWriter

# --- generative validation deps ---
from sklearn.metrics import pairwise_distances
from sklearn.linear_model import Ridge
from scipy.stats import pearsonr


# ----------------------------
# Seed
# ----------------------------
def set_seed(seed: int = 42):
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

# ----------------------------
# Preprocessing
# ----------------------------
class CVAEPreprocessor:
    """
    Fits on TRAIN ONLY:
      - conditioning: median impute + StandardScaler
      - continuous targets: median impute + StandardScaler
      - binary targets (optional): most_frequent impute, kept as 0/1
    """
    def __init__(self):
        self.c_imputer = SimpleImputer(strategy="median")
        self.c_scaler = StandardScaler()

        self.yc_imputer = SimpleImputer(strategy="median")
        self.yc_scaler = StandardScaler()

        self.yb_imputer = SimpleImputer(strategy="most_frequent")
        self.has_bin = False
        self.fitted_ = False

    def fit(self, df: pd.DataFrame, c_cols, y_cont_cols, y_bin_cols=None):
        # conditioning
        C = self.c_imputer.fit_transform(df[c_cols])
        self.c_scaler.fit(C)

        # continuous targets
        Yc = self.yc_imputer.fit_transform(df[y_cont_cols])
        self.yc_scaler.fit(Yc)

        # binary targets
        if y_bin_cols and len(y_bin_cols) > 0:
            self.yb_imputer.fit(df[y_bin_cols])
            self.has_bin = True

        self.fitted_ = True
        return self

    def transform(self, df: pd.DataFrame, c_cols, y_cont_cols, y_bin_cols=None):
        assert self.fitted_, "Call fit() first."

        C = self.c_scaler.transform(self.c_imputer.transform(df[c_cols]))
        Yc = self.yc_scaler.transform(self.yc_imputer.transform(df[y_cont_cols]))

        if y_bin_cols and len(y_bin_cols) > 0:
            Yb = self.yb_imputer.transform(df[y_bin_cols]).astype(np.float32)
        else:
            Yb = None

        return C.astype(np.float32), Yc.astype(np.float32), Yb

    def inverse_continuous(self, Yc_scaled: np.ndarray) -> np.ndarray:
        """Scaled -> original continuous units."""
        return self.yc_scaler.inverse_transform(Yc_scaled)

# ----------------------------
# Dataset
# ----------------------------
class CVAEDataset(Dataset):
    def __init__(self, C, Yc, Yb=None):
        self.C = C
        self.Yc = Yc
        self.Yb = Yb

    def __len__(self):
        return len(self.C)

    def __getitem__(self, idx):
        if self.Yb is None:
            return self.C[idx], self.Yc[idx]
        return self.C[idx], self.Yc[idx], self.Yb[idx]

# ----------------------------
# Model
# ----------------------------
class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim, dropout=0.1):
        super().__init__()
        layers = []
        d = in_dim
        for h in hidden:
            layers += [nn.Linear(d, h), nn.ReLU(), nn.Dropout(dropout)]
            d = h
        layers.append(nn.Linear(d, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

class CVAE(nn.Module):
    """
    Encoder: q(z | y_cont, c) -> mu, logvar
    Decoder: p(y_cont, y_bin | z, c)
    """
    def __init__(self, c_dim, y_cont_dim, z_dim=16, hidden=(256, 256), bin_dim=0, dropout=0.1):
        super().__init__()
        self.z_dim = z_dim
        self.c_dim = c_dim
        self.y_cont_dim = y_cont_dim
        self.bin_dim = bin_dim

        # Encoder takes [y_cont, c]
        self.encoder = MLP(
            in_dim=y_cont_dim + c_dim,
            hidden=hidden,
            out_dim=2 * z_dim,
            dropout=dropout
        )

        # Decoder takes [z, c] -> y_cont
        self.decoder_y = MLP(
            in_dim=z_dim + c_dim,
            hidden=hidden,
            out_dim=y_cont_dim,
            dropout=dropout
        )

        # Optional binary head
        self.decoder_bin = None
        if bin_dim > 0:
            self.decoder_bin = MLP(
                in_dim=z_dim + c_dim,
                hidden=hidden,
                out_dim=bin_dim,
                dropout=dropout
            )

    def encode(self, y_cont, c):
        h = torch.cat([y_cont, c], dim=1)
        params = self.encoder(h)
        mu, logvar = params[:, : self.z_dim], params[:, self.z_dim :]
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, c):
        h = torch.cat([z, c], dim=1)
        y_cont_hat = self.decoder_y(h)
        yb_logits = self.decoder_bin(h) if self.decoder_bin is not None else None
        return y_cont_hat, yb_logits

    def forward(self, y_cont, c):
        mu, logvar = self.encode(y_cont, c)
        z = self.reparameterize(mu, logvar)
        y_cont_hat, yb_logits = self.decode(z, c)
        return y_cont_hat, yb_logits, mu, logvar

# ----------------------------
# Loss
# ----------------------------
def kl_div(mu, logvar):
    # 0.5 * sum(exp(logvar) + mu^2 - 1 - logvar)
    return 0.5 * torch.sum(torch.exp(logvar) + mu**2 - 1.0 - logvar, dim=1)

def beta_schedule(epoch, warmup_epochs=10, max_beta=1.0):
    if warmup_epochs <= 0:
        return max_beta
    return max_beta * min(1.0, (epoch + 1) / warmup_epochs)

def cvae_loss(yc_hat, yc_true, mu, logvar, yb_logits=None, yb_true=None, beta=1.0, bin_weight=1.0):
    # reconstruction on scaled continuous targets
    rec_yc = F.mse_loss(yc_hat, yc_true, reduction="none").sum(dim=1)

    rec_yb = torch.zeros_like(rec_yc)
    if yb_logits is not None and yb_true is not None:
        rec_yb = F.binary_cross_entropy_with_logits(yb_logits, yb_true, reduction="none").sum(dim=1)

    kl = kl_div(mu, logvar)
    loss = rec_yc + bin_weight * rec_yb + beta * kl

    # Return mean + per-batch metrics
    return loss.mean(), {
        "loss": float(loss.mean().detach().cpu()),
        "rec_yc": float(rec_yc.mean().detach().cpu()),
        "rec_yb": float(rec_yb.mean().detach().cpu()) if (yb_logits is not None and yb_true is not None) else 0.0,
        "kl": float(kl.mean().detach().cpu()),
    }


# ----------------------------
# Generation helpers
# ----------------------------
@torch.no_grad()
def generate_for_rows(model, prep, df_rows: pd.DataFrame, c_cols, *, n_samples=100, device=None):
    """
    Given df_rows with conditioning columns, generate n_samples synthetic tracks per row.
    Returns:
      y_cont_samples_original_units: shape (n_rows, n_samples, y_cont_dim)
      y_bin_probs: shape (n_rows, n_samples, y_bin_dim) or None
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    model.eval()
    model.to(device)

    # Transform conditioning only
    C = prep.c_scaler.transform(prep.c_imputer.transform(df_rows[c_cols])).astype(np.float32)

    C_t = torch.tensor(C, dtype=torch.float32, device=device)  # (n_rows, c_dim)
    n_rows = C_t.size(0)

    # Repeat each row n_samples times
    C_rep = C_t.unsqueeze(1).repeat(1, n_samples, 1).reshape(n_rows * n_samples, -1)
    z = torch.randn((n_rows * n_samples, model.z_dim), device=device)

    yc_hat_scaled, yb_logits = model.decode(z, C_rep)

    yc_hat_scaled = yc_hat_scaled.detach().cpu().numpy().reshape(n_rows, n_samples, -1)
    yc_hat = prep.inverse_continuous(
        yc_hat_scaled.reshape(-1, yc_hat_scaled.shape[-1])
    ).reshape(n_rows, n_samples, -1)

    yb_probs = None
    if yb_logits is not None:
        yb_probs = torch.sigmoid(yb_logits).detach().cpu().numpy().reshape(n_rows, n_samples, -1)

    return yc_hat, yb_probs


# ///////////////////////////////////////////////////////////////////////////////////////////////////////
# ============================
# GENERATIVE VALIDATION
# Loss curves alone do NOT validate a generative model.
# This section adds:
#   1) Sample diversity metrics
#   2) Correlation vs real data
#   3) Downstream task performance (e.g. popularity ranking)
#
# These log into the SAME TensorBoard run created in fit_cvae.
# ============================

@torch.no_grad()
def log_sample_diversity_to_tb(
    writer,
    model,
    prep,
    df_eval,
    c_cols,
    epoch,
    *,
    n_rows=10,
    n_samples=100,
    device=None,
):
    """
    Sample diversity metrics
    Detects mode collapse.

    Logs:
      - gen/diversity_mean_feature_std
      - gen/diversity_mean_pairwise_dist
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    df_sub = df_eval.sample(min(n_rows, len(df_eval)))
    yc_samples, _ = generate_for_rows(model, prep, df_sub, c_cols, n_samples=n_samples, device=device)

    flat = yc_samples.reshape(-1, yc_samples.shape[-1])
    mean_std = float(flat.std(axis=0).mean())
    mean_pwd = float(pairwise_distances(flat).mean())

    writer.add_scalar("gen/diversity_mean_feature_std", mean_std, epoch)
    writer.add_scalar("gen/diversity_mean_pairwise_dist", mean_pwd, epoch)


@torch.no_grad()
def log_correlation_to_tb(
    writer,
    model,
    prep,
    df_eval,
    c_cols,
    y_cont_cols,
    epoch,
    *,
    n_samples=100,
    device=None,
):
    """
    Correlation vs real data

    For each eval row:
      - generate samples
      - compare generated mean to real track
    Logs:
      - gen/mean_abs_feature_corr
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    yc_samples, _ = generate_for_rows(model, prep, df_eval, c_cols, n_samples=n_samples, device=device)
    gen_mean = yc_samples.mean(axis=1)
    real = df_eval[y_cont_cols].values

    corrs = []
    for i in range(gen_mean.shape[1]):
        try:
            c, _ = pearsonr(gen_mean[:, i], real[:, i])
            if np.isfinite(c):
                corrs.append(abs(c))
        except Exception:
            pass

    mean_abs_corr = float(np.mean(corrs)) if corrs else 0.0
    writer.add_scalar("gen/mean_abs_feature_corr", mean_abs_corr, epoch)


def log_popularity_ranking_to_tb(
    writer,
    model,
    prep,
    df_train,
    df_eval,
    c_cols,
    y_cont_cols,
    popularity_col,
    epoch,
    *,
    n_samples=100,
    device=None,
):
    """
    Downstream task performance (e.g. popularity ranking)

    Trains a popularity regressor on REAL tracks,
    then evaluates ranking quality on GENERATED samples.

    Logs:
      - gen/popularity_rank_corr
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    if popularity_col not in df_train.columns or popularity_col not in df_eval.columns:
        # don't crash training if you haven't joined popularity yet
        writer.add_scalar("gen/popularity_rank_corr", np.nan, epoch)
        return

    pop_model = Ridge(alpha=1.0)
    pop_model.fit(df_train[y_cont_cols], df_train[popularity_col])

    yc_samples, _ = generate_for_rows(model, prep, df_eval, c_cols, n_samples=n_samples, device=device)

    n_rows = yc_samples.shape[0]
    scores = pop_model.predict(yc_samples.reshape(-1, yc_samples.shape[-1]))
    scores = scores.reshape(n_rows, n_samples)

    best_synth = scores.max(axis=1)
    real_pop = df_eval[popularity_col].values

    try:
        corr, _ = pearsonr(best_synth, real_pop)
    except Exception:
        corr = np.nan

    writer.add_scalar("gen/popularity_rank_corr", float(corr), epoch)


# ----------------------------
# Train / Eval
# ----------------------------
@torch.no_grad()
def evaluate(model, loader, device, beta=1.0, bin_weight=1.0):
    model.eval()
    totals = {"loss": 0.0, "rec_yc": 0.0, "rec_yb": 0.0, "kl": 0.0}
    n = 0

    for batch in loader:
        if len(batch) == 2:
            c, yc = batch
            yb = None
        else:
            c, yc, yb = batch

        c = c.to(device)
        yc = yc.to(device)
        yb = yb.to(device) if yb is not None else None

        yc_hat, yb_logits, mu, logvar = model(yc, c)
        _, m = cvae_loss(yc_hat, yc, mu, logvar, yb_logits, yb, beta=beta, bin_weight=bin_weight)

        bs = c.size(0)
        n += bs
        for k in totals:
            totals[k] += m[k] * bs

    return {k: totals[k] / max(n, 1) for k in totals}

def train_cvae(
    model,
    train_loader,
    val_loader,
    device,
    writer: SummaryWriter,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    grad_clip=5.0,
    log_hists_every=0,
    y_cont_cols=None,
    prep=None,
    # --- additive only: used for generative validation logging ---
    df_train=None,
    df_val=None,
    c_cols=None,
    popularity_col="track_popularity",
    gen_eval_every=5,
    gen_eval_n_samples=100,
    gen_eval_n_rows=10,
):
    """
    log_hists_every:
      - 0 disables histogram logging
      - otherwise logs generated histograms every N epochs (requires y_cont_cols + prep)
    """
    model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr)

    best = None
    best_state = None
    global_step = 0

    for epoch in range(epochs):
        model.train()
        beta = beta_schedule(epoch, warmup_epochs=warmup_epochs, max_beta=max_beta)

        totals = {"loss": 0.0, "rec_yc": 0.0, "rec_yb": 0.0, "kl": 0.0}
        n = 0

        for batch in train_loader:
            if len(batch) == 2:
                c, yc = batch # Conditional variables, y_conditionals
                yb = None     # y-bin conditional
            else:
                c, yc, yb = batch

            c = c.to(device)
            yc = yc.to(device)
            yb = yb.to(device) if yb is not None else None

            opt.zero_grad(set_to_none=True)
            yc_hat, yb_logits, mu, logvar = model(yc, c) # Predicted y_conditionals, y-bin logit predictions, error, logvariance
            loss, m = cvae_loss(yc_hat, yc, mu, logvar, yb_logits, yb, beta=beta, bin_weight=bin_weight)
            loss.backward()
            if grad_clip is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            opt.step()

            bs = c.size(0)
            n += bs
            global_step += 1

            # accumulate epoch metrics
            for k in totals:
                totals[k] += m[k] * bs

        train_m = {k: totals[k] / max(n, 1) for k in totals}
        val_m = evaluate(model, val_loader, device, beta=1.0, bin_weight=bin_weight) if val_loader is not None else None

        # ---------------------------------------
        # TensorBoard scalar logging
        # ---------------------------------------
        writer.add_scalar("loss/train", train_m["loss"], epoch)
        writer.add_scalar("recon_yc/train", train_m["rec_yc"], epoch)
        writer.add_scalar("recon_yb/train", train_m["rec_yb"], epoch)
        writer.add_scalar("kl/train", train_m["kl"], epoch)
        writer.add_scalar("beta", beta, epoch)

        if val_m is not None:
            writer.add_scalar("loss/val", val_m["loss"], epoch)
            writer.add_scalar("recon_yc/val", val_m["rec_yc"], epoch)
            writer.add_scalar("recon_yb/val", val_m["rec_yb"], epoch)
            writer.add_scalar("kl/val", val_m["kl"], epoch)

        # Optional latent stats (useful for collapse debugging)
        # We log from the last batch of the epoch (good enough)
        with torch.no_grad():
            writer.add_scalar("latent/mu_mean", float(mu.mean().detach().cpu()), epoch)
            writer.add_scalar("latent/mu_std", float(mu.std().detach().cpu()), epoch)
            writer.add_scalar("latent/logvar_mean", float(logvar.mean().detach().cpu()), epoch)

        # Optional histogram logging (off by default)
        if log_hists_every and (epoch % log_hists_every == 0) and (prep is not None) and (y_cont_cols is not None):
            # Log histograms of reconstructed yc_hat (scaled space) for a quick view of collapse/noise
            # Use last batch's yc_hat
            yc_hat_np = yc_hat.detach().cpu().numpy()
            # unscale to original units for interpretability
            yc_hat_unscaled = prep.inverse_continuous(yc_hat_np)
            for j, feat in enumerate(y_cont_cols[: min(10, len(y_cont_cols))]):
                writer.add_histogram(f"recon_unscaled/{feat}", yc_hat_unscaled[:, j], epoch)

        # --------------------------------------------------
        # GENERATIVE VALIDATION (offline checks)
        # Loss curves alone cannot validate a generative model.
        # --------------------------------------------------
        if (
            gen_eval_every
            and (epoch % gen_eval_every == 0)
            and (prep is not None)
            and (y_cont_cols is not None)
            and (df_train is not None)
            and (df_val is not None)
            and (c_cols is not None)
        ):
            log_sample_diversity_to_tb(
                writer, model, prep, df_val, c_cols, epoch,
                n_rows=gen_eval_n_rows,
                n_samples=gen_eval_n_samples,
                device=device
            )
            log_correlation_to_tb(
                writer, model, prep, df_val, c_cols, y_cont_cols, epoch,
                n_samples=gen_eval_n_samples,
                device=device
            )
            log_popularity_ranking_to_tb(
                writer, model, prep,
                df_train, df_val,
                c_cols, y_cont_cols,
                popularity_col=popularity_col,
                epoch=epoch,
                n_samples=gen_eval_n_samples,
                device=device
            )

        score = val_m["loss"] if val_m is not None else train_m["loss"]
        if best is None or score < best:
            best = score
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        msg = (
            f"Epoch {epoch+1:02d}/{epochs} | "
            f"train loss {train_m['loss']:.4f} "
            f"(rec_yc {train_m['rec_yc']:.4f}, "
            f"rec_yb {train_m['rec_yb']:.4f}, "
            f"kl {train_m['kl']:.4f}, "
            f"beta {beta:.3f})"
        )
        if val_m is not None:
            msg += (
                f" | val loss {val_m['loss']:.4f} "
                f"(rec_yc {val_m['rec_yc']:.4f}, rec_yb {val_m['rec_yb']:.4f}, kl {val_m['kl']:.4f})"
            )
        print(msg)

    if best_state is not None:
        model.load_state_dict(best_state)
    return model

# ----------------------------
# Fit helper
# ----------------------------
def fit_cvae(
    df_train: pd.DataFrame,
    df_val: pd.DataFrame,
    c_cols,
    y_cont_cols,
    y_bin_cols=None,
    *,
    z_dim=16,
    hidden=(256, 256),
    dropout=0.1,
    batch_size=512,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    num_workers=0,
    seed=42,
    log_root="runs",
    run_name=None,
    log_hists_every=0
):
    """
    Returns: (model, prep, writer)
    """
    set_seed(seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    y_bin_cols = y_bin_cols or []

    # Unique run dir
    if run_name is None:
        ts = time.strftime("%Y%m%d_%H%M%S")
        run_name = f"cvae_tracks_z{z_dim}_h{'-'.join(map(str, hidden))}_{ts}"
    log_dir = os.path.join(log_root, run_name)
    writer = SummaryWriter(log_dir=log_dir)

    # Fit preprocessors on TRAIN ONLY
    prep = CVAEPreprocessor().fit(df_train, c_cols, y_cont_cols, y_bin_cols)

    # Transform to numpy arrays
    C_tr, Yc_tr, Yb_tr = prep.transform(df_train, c_cols, y_cont_cols, y_bin_cols)
    C_va, Yc_va, Yb_va = prep.transform(df_val, c_cols, y_cont_cols, y_bin_cols)

    # Datasets / Loaders
    ds_tr = CVAEDataset(C_tr, Yc_tr, Yb_tr)
    ds_va = CVAEDataset(C_va, Yc_va, Yb_va)

    train_loader = DataLoader(ds_tr, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)
    val_loader = DataLoader(ds_va, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=True)

    # Model
    model = CVAE(
        c_dim=len(c_cols),
        y_cont_dim=len(y_cont_cols),
        z_dim=z_dim,
        hidden=hidden,
        bin_dim=len(y_bin_cols),
        dropout=dropout
    )

    # Train
    model = train_cvae(
        model,
        train_loader,
        val_loader,
        device=device,
        writer=writer,
        epochs=epochs,
        lr=lr,
        warmup_epochs=warmup_epochs,
        max_beta=max_beta,
        bin_weight=bin_weight,
        log_hists_every=log_hists_every,
        y_cont_cols=y_cont_cols,
        prep=prep,
        # --- generative validation wiring ---
        df_train=df_train,
        df_val=df_val,
        c_cols=c_cols,
        popularity_col="track_popularity",
        gen_eval_every=5,
        gen_eval_n_samples=100,
        gen_eval_n_rows=10
    )

    # Optional: log model graph (can fail in some cases; safe to skip)
    try:
        example_c = torch.tensor(C_tr[:2], dtype=torch.float32, device=device)
        example_y = torch.tensor(Yc_tr[:2], dtype=torch.float32, device=device)
        writer.add_graph(model, (example_y, example_c))
    except Exception:
        pass

    return model, prep, writer

In [12]:
# ======================================================================================----------------
# QUICK VALIDATION RUN OF GENERATION METRIC
# ======================================================================================----------------
"""
# You must define:
# df_test
# popularity_col = "track_popularity"  # example

print("=== Sample Diversity ===")
print(sample_diversity_metrics(model, prep, df_test, c_cols))

print("\n=== Generated vs Real Correlation ===")
print(generated_vs_real_correlation(model, prep, df_test, c_cols, y_cont_cols))

print("\n=== Downstream Popularity Ranking ===")
print(
    downstream_popularity_ranking(
        model, prep,
        df_train, df_test,
        c_cols, y_cont_cols,
        popularity_col=popularity_col
    )
)
"""

'\n# You must define:\n# df_test\n# popularity_col = "track_popularity"  # example\n\nprint("=== Sample Diversity ===")\nprint(sample_diversity_metrics(model, prep, df_test, c_cols))\n\nprint("\n=== Generated vs Real Correlation ===")\nprint(generated_vs_real_correlation(model, prep, df_test, c_cols, y_cont_cols))\n\nprint("\n=== Downstream Popularity Ranking ===")\nprint(\n    downstream_popularity_ranking(\n        model, prep,\n        df_train, df_test,\n        c_cols, y_cont_cols,\n        popularity_col=popularity_col\n    )\n)\n'

In [ ]:
# ======================================================================================
# QUICK START
# ======================================================================================

# Conditioning feature colums
# Or the things that we want to tell the model about our artists and their typical tracks 
c_cols = [
    # graph geometry
    "cos_sim_src_dst",
    "l2_dist_src_dst",
    
    # artist popularity
    "popularity_src",
    "popularity_dst",
    
    # neighbor features
    "mean_topk_cos_dstnbr_src",
    "mean_topk_cos_srcnbr_dst",

    # graph reachability
    "shared_neighbors",
    
]

### TODO:
### STOP HERE FOR NOW, GET THESE ATTRIBUTES AFTER WE KNOW THE MODEL CAN RUN
"""
    # artist A aggregates
    "src_mean_danceability",
    "src_mean_energy",
    "src_mean_valence",
    "src_mean_acousticness",
    "src_mean_tempo",

    # artist B aggregates
    "dst_mean_danceability",
    "dst_mean_energy",
    "dst_mean_valence",
    "dst_mean_acousticness",
    "dst_mean_tempo",

    # artist blend signals
    "abs_diff_danceability",
    "abs_diff_energy",
    "abs_diff_valence",
    "abs_diff_acousticness",
    "abs_diff_tempo",
]
"""

# What we are trying to predict
y_cont_cols = [
    'danceability',
     
    'gender_female','gender_male',
    
    'genre_dortmund_alternative','genre_dortmund_blues','genre_dortmund_electronic',
    'genre_dortmund_folkcountry','genre_dortmund_funksoulrnb','genre_dortmund_jazz',
    'genre_dortmund_pop','genre_dortmund_raphiphop','genre_dortmund_rock',
    'genre_electronic_ambient','genre_electronic_dnb','genre_electronic_house',
    'genre_electronic_techno','genre_electronic_trance','genre_rosamerica_cla',
    'genre_rosamerica_dan','genre_rosamerica_hip','genre_rosamerica_jaz','genre_rosamerica_pop',
    'genre_rosamerica_rhy','genre_rosamerica_roc','genre_rosamerica_spe',
    'genre_tzanetakis_blu','genre_tzanetakis_cla','genre_tzanetakis_cou','genre_tzanetakis_dis',
    'genre_tzanetakis_hip','genre_tzanetakis_jaz','genre_tzanetakis_met','genre_tzanetakis_pop',
    'genre_tzanetakis_reg','genre_tzanetakis_roc',
    
    'ismir04_rhythm_chachacha','ismir04_rhythm_jive','ismir04_rhythm_quickstep',
    'ismir04_rhythm_rumba_american','ismir04_rhythm_rumba_international','ismir04_rhythm_rumba_misc',
    'ismir04_rhythm_samba','ismir04_rhythm_tango','ismir04_rhythm_viennesewaltz','ismir04_rhythm_waltz',
    
    'mood_acoustic','mood_aggressive','mood_electronic','mood_happy',
    'mood_party','mood_relaxed','mood_sad',
    
    'moods_mirex_cluster1','moods_mirex_cluster2',
    'moods_mirex_cluster3','moods_mirex_cluster4','moods_mirex_cluster5',
    
    'timbre_bright','timbre_dark',
    
    'tonal_atonal_atonal','tonal_atonal_tonal',
    
    'voice_instrumental_instrumental','voice_instrumental_voice'
]
y_bin_cols = []

# You must already have df_train and df_val:
model, prep, writer = fit_cvae(
    df_train, df_val,
    c_cols=c_cols,
    y_cont_cols=y_cont_cols,
    y_bin_cols=y_bin_cols,
    z_dim=16,
    hidden=(256, 256),
    dropout=0.1,
    batch_size=512,
    epochs=30,
    lr=1e-3,
    warmup_epochs=10,
    max_beta=1.0,
    bin_weight=1.0,
    log_root="runs",
    run_name=None,         # auto name with timestamp
    log_hists_every=0      # set to e.g. 5 to log histograms every 5 epochs
)

# Generate samples for a few candidate pairs/rows:
y_cont_samples, y_bin_probs = generate_for_rows(
    model, prep, df_val.head(5), c_cols, n_samples=200
)

print("y_cont_samples:", y_cont_samples.shape)  # (n_rows, n_samples, y_cont_dim)
print("y_bin_probs:", None if y_bin_probs is None else y_bin_probs.shape)

# Close writer when done (good practice in notebooks)
writer.close()

/home/jonnym/.local/lib/python3.11/site-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Epoch 01/30 | train loss 16.9304 (rec_yc 14.5355, rec_yb 0.0000, kl 23.9489, beta 0.100) | val loss 28.5907 (rec_yc 4.7582, rec_yb 0.0000, kl 23.8325)

/home/jonnym/.local/lib/python3.11/site-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Epoch 02/30 | train loss 10.7078 (rec_yc 7.0477, rec_yb 0.0000, kl 18.3001, beta 0.200) | val loss 21.4766 (rec_yc 4.0146, rec_yb 0.0000, kl 17.4620)
Epoch 03/30 | train loss 11.0399 (rec_yc 6.5839, rec_yb 0.0000, kl 14.8534, beta 0.300) | val loss 18.1332 (rec_yc 3.9104, rec_yb 0.0000, kl 14.2228)
Epoch 04/30 | train loss 11.6445 (rec_yc 6.4945, rec_yb 0.0000, kl 12.8749, beta 0.400) | val loss 16.5559 (rec_yc 4.0574, rec_yb 0.0000, kl 12.4985)
Epoch 05/30 | train loss 12.3292 (rec_yc 6.5387, rec_yb 0.0000, kl 11.5810, beta 0.500) | val loss 15.4907 (rec_yc 4.1669, rec_yb 0.0000, kl 11.3238)
Epoch 06/30 | train loss 12.9849 (rec_yc 6.6013, rec_yb 0.0000, kl 10.6392, beta 0.600) | val loss 14.6261 (rec_yc 4.4001, rec_yb 0.0000, kl 10.2260)
Epoch 07/30 | train loss 13.7068 (rec_yc 6.7697, rec_yb 0.0000, kl 9.9101, beta 0.700) | val loss 14.2182 (rec_yc 4.6178, rec_yb 0.0000, kl 9.6004)
Epoch 08/30 | train loss 14.3850 (rec_yc 6.9216, rec_yb 0.0000, kl 9.3293, beta 0.800) | val loss 13.8987 (rec_yc 4.8827, rec_yb 0.0000, kl 9.0159)
Epoch 09/30 | train loss 15.0885 (rec_yc 7.1176, rec_yb 0.0000, kl 8.8566, beta 0.900) | val loss 13.6081 (rec_yc 5.2172, rec_yb 0.0000, kl 8.3909)
Epoch 10/30 | train loss 15.7395 (rec_yc 7.3099, rec_yb 0.0000, kl 8.4295, beta 1.000) | val loss 13.3870 (rec_yc 5.1253, rec_yb 0.0000, kl 8.2617)
Epoch 11/30 | train loss 15.5532 (rec_yc 7.2435, rec_yb 0.0000, kl 8.3097, beta 1.000) | val loss 13.3373 (rec_yc 5.0616, rec_yb 0.0000, kl 8.2758)

/home/jonnym/.local/lib/python3.11/site-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Epoch 12/30 | train loss 15.3800 (rec_yc 7.1517, rec_yb 0.0000, kl 8.2283, beta 1.000) | val loss 13.1341 (rec_yc 5.1118, rec_yb 0.0000, kl 8.0224)
Epoch 13/30 | train loss 15.2392 (rec_yc 7.0862, rec_yb 0.0000, kl 8.1530, beta 1.000) | val loss 12.9691 (rec_yc 5.0104, rec_yb 0.0000, kl 7.9587)
Epoch 14/30 | train loss 15.1338 (rec_yc 7.0215, rec_yb 0.0000, kl 8.1122, beta 1.000) | val loss 12.9017 (rec_yc 4.9713, rec_yb 0.0000, kl 7.9304)
Epoch 15/30 | train loss 15.0704 (rec_yc 6.9914, rec_yb 0.0000, kl 8.0790, beta 1.000) | val loss 12.8581 (rec_yc 5.1354, rec_yb 0.0000, kl 7.7227)
Epoch 16/30 | train loss 14.9437 (rec_yc 6.9240, rec_yb 0.0000, kl 8.0197, beta 1.000) | val loss 12.7531 (rec_yc 5.0480, rec_yb 0.0000, kl 7.7050)
Epoch 17/30 | train loss 14.8759 (rec_yc 6.8892, rec_yb 0.0000, kl 7.9867, beta 1.000) | val loss 12.7141 (rec_yc 4.9415, rec_yb 0.0000, kl 7.7726)
Epoch 18/30 | train loss 14.8407 (rec_yc 6.8821, rec_yb 0.0000, kl 7.9587, beta 1.000) | val loss 12.6152 (rec_yc 4.7570, rec_yb 0.0000, kl 7.8581)
Epoch 19/30 | train loss 14.7893 (rec_yc 6.8528, rec_yb 0.0000, kl 7.9365, beta 1.000) | val loss 12.7512 (rec_yc 4.9219, rec_yb 0.0000, kl 7.8293)
Epoch 20/30 | train loss 14.6759 (rec_yc 6.7821, rec_yb 0.0000, kl 7.8938, beta 1.000) | val loss 12.4752 (rec_yc 4.6829, rec_yb 0.0000, kl 7.7923)
Epoch 21/30 | train loss 14.6507 (rec_yc 6.7686, rec_yb 0.0000, kl 7.8821, beta 1.000) | val loss 12.5987 (rec_yc 4.8932, rec_yb 0.0000, kl 7.7055)

/home/jonnym/.local/lib/python3.11/site-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Epoch 22/30 | train loss 14.6140 (rec_yc 6.7576, rec_yb 0.0000, kl 7.8565, beta 1.000) | val loss 12.3779 (rec_yc 4.6084, rec_yb 0.0000, kl 7.7694)
Epoch 23/30 | train loss 14.5419 (rec_yc 6.6946, rec_yb 0.0000, kl 7.8473, beta 1.000) | val loss 12.3401 (rec_yc 4.5850, rec_yb 0.0000, kl 7.7551)
Epoch 24/30 | train loss 14.4769 (rec_yc 6.6570, rec_yb 0.0000, kl 7.8199, beta 1.000) | val loss 12.3560 (rec_yc 4.7239, rec_yb 0.0000, kl 7.6322)
Epoch 25/30 | train loss 14.4418 (rec_yc 6.6343, rec_yb 0.0000, kl 7.8074, beta 1.000) | val loss 12.3764 (rec_yc 4.8380, rec_yb 0.0000, kl 7.5385)
Epoch 26/30 | train loss 14.4434 (rec_yc 6.6493, rec_yb 0.0000, kl 7.7940, beta 1.000) | val loss 12.1985 (rec_yc 4.4669, rec_yb 0.0000, kl 7.7316)
Epoch 27/30 | train loss 14.3677 (rec_yc 6.5928, rec_yb 0.0000, kl 7.7749, beta 1.000) | val loss 12.3113 (rec_yc 4.7814, rec_yb 0.0000, kl 7.5299)
Epoch 28/30 | train loss 14.3358 (rec_yc 6.5747, rec_yb 0.0000, kl 7.7611, beta 1.000) | val loss 12.1831 (rec_yc 4.6518, rec_yb 0.0000, kl 7.5314)
Epoch 29/30 | train loss 14.3334 (rec_yc 6.5862, rec_yb 0.0000, kl 7.7472, beta 1.000) | val loss 12.2930 (rec_yc 4.6516, rec_yb 0.0000, kl 7.6415)
Epoch 30/30 | train loss 14.2869 (rec_yc 6.5399, rec_yb 0.0000, kl 7.7470, beta 1.000) | val loss 12.2397 (rec_yc 4.6716, rec_yb 0.0000, kl 7.5682)
y_cont_samples: (5, 200, 63)
y_bin_probs: None

def log_sample_diversity_to_tb(
    writer,
    model, prep, df_test, c_cols,
    epoch,
    n_samples=100,
    device=None
):
    metrics = sample_diversity_metrics(
        model, prep, df_test, c_cols,
        n_samples=n_samples,
        device=device
    )

    writer.add_scalar("generative/diversity/mean_feature_std", metrics["mean_feature_std"], epoch)
    writer.add_scalar("generative/diversity/mean_pairwise_dist", metrics["mean_pairwise_dist"], epoch)


def log_correlation_to_tb(
    writer,
    model, prep, df_test,
    c_cols, y_cont_cols,
    epoch,
    n_samples=100,
    device=None
):
    corr_df = generated_vs_real_correlation(
        model, prep, df_test, c_cols, y_cont_cols,
        n_samples=n_samples,
        device=device
    )

    for _, row in corr_df.iterrows():
        writer.add_scalar(
            f"generative/correlation/{row['feature']}",
            row["corr"],
            epoch
        )


def log_popularity_ranking_to_tb(
    writer,
    model, prep,
    df_train, df_test,
    c_cols, y_cont_cols,
    popularity_col,
    epoch,
    n_samples=100,
    device=None
):
    metrics = downstream_popularity_ranking(
        model, prep,
        df_train, df_test,
        c_cols, y_cont_cols,
        popularity_col,
        n_samples=n_samples,
        device=device
    )

    writer.add_scalar("generative/popularity/corr", metrics["popularity_rank_corr"], epoch)
    writer.add_scalar("generative/popularity/mean_best_synth", metrics["mean_best_synth_pop"], epoch)
    writer.add_scalar("generative/popularity/mean_real", metrics["mean_real_pop"], epoch)

In [14]:
pd.set_option("display.max_columns",None)
df_train.head(2)

,src,dst,recording_gid,recording_id,recording_gid,danceability,gender_female,gender_male,genre_dortmund_alternative,genre_dortmund_blues,genre_dortmund_electronic,genre_dortmund_folkcountry,genre_dortmund_funksoulrnb,genre_dortmund_jazz,genre_dortmund_pop,genre_dortmund_raphiphop,genre_dortmund_rock,genre_electronic_ambient,genre_electronic_dnb,genre_electronic_house,genre_electronic_techno,genre_electronic_trance,genre_rosamerica_cla,genre_rosamerica_dan,genre_rosamerica_hip,genre_rosamerica_jaz,genre_rosamerica_pop,genre_rosamerica_rhy,genre_rosamerica_roc,genre_rosamerica_spe,genre_tzanetakis_blu,genre_tzanetakis_cla,genre_tzanetakis_cou,genre_tzanetakis_dis,genre_tzanetakis_hip,genre_tzanetakis_jaz,genre_tzanetakis_met,genre_tzanetakis_pop,genre_tzanetakis_reg,genre_tzanetakis_roc,ismir04_rhythm_chachacha,ismir04_rhythm_jive,ismir04_rhythm_quickstep,ismir04_rhythm_rumba_american,ismir04_rhythm_rumba_international,ismir04_rhythm_rumba_misc,ismir04_rhythm_samba,ismir04_rhythm_tango,ismir04_rhythm_viennesewaltz,ismir04_rhythm_waltz,mood_acoustic,mood_aggressive,mood_electronic,mood_happy,mood_party,mood_relaxed,mood_sad,moods_mirex_cluster1,moods_mirex_cluster2,moods_mirex_cluster3,moods_mirex_cluster4,moods_mirex_cluster5,timbre_bright,timbre_dark,tonal_atonal_atonal,tonal_atonal_tonal,voice_instrumental_instrumental,voice_instrumental_voice,Unnamed: 0,cos_sim_src_dst,l2_dist_src_dst,dot_src_dst,abs_diff_mean,abs_diff_max,popularity_src,popularity_dst,max_cos_srcnbr_dst,mean_cos_srcnbr_dst,mean_topk_cos_srcnbr_dst,num_src_neighbors,max_cos_dstnbr_src,mean_cos_dstnbr_src,mean_topk_cos_dstnbr_src,num_dst_neighbors,shared_neighbors,jaccard_neighbors,adamic_adar,preferential_attachment,label
47912,d6652e7b-33fe-49ef-8336-4c863b4f996f,70248960-cb53-4ea4-943a-edb18f7d336f,7cd30d07-bb4d-489e-b344-59ec495e87cf,8399126,7cd30d07-bb4d-489e-b344-59ec495e87cf,0.512898,0.042456,0.957544,0.186921,0.020585,0.694396,0.043608,0.002623,0.003288,0.006884,0.001517,0.040178,0.626223,0.025458,0.029589,0.003511,0.315219,0.013309,0.003257,0.001388,0.002096,0.032288,0.002949,0.943963,0.000750,6.266134e-02,3.481696e-02,1.044758e-01,7.843216e-02,1.569244e-01,0.313975,4.481665e-02,0.062736,0.062736,7.842588e-02,0.171415,0.190374,0.029310,0.025382,0.024330,0.016673,0.045510,0.228859,0.246032,0.022116,0.021949,0.571975,0.332218,0.747347,0.464710,0.060475,0.142891,0.169873,0.217364,0.146618,0.278860,0.187285,0.921753,0.078247,0.026798,0.973202,0.010952,0.989048,8015.0,0.692571,0.784129,0.692571,0.106396,0.426108,3.2525,7.1900,1.0,1.000000,1.000000,1.0,1.0,0.781695,0.781695,2.0,0.0,0.0,0.0,3.0,1.0
133331,98b95966-64db-4631-8b9f-8aa66f32cc98,9b891046-35af-4eb0-a058-eba4c9b8d01f,32b711c0-9dd7-489f-b53d-eabe8e2abb13,3284024,32b711c0-9dd7-489f-b53d-eabe8e2abb13,0.012450,0.129408,0.870592,0.004938,0.707456,0.001510,0.024642,0.038085,0.022553,0.009564,0.176120,0.015133,0.972281,0.006565,0.012117,0.007280,0.001756,0.541513,0.003934,0.054136,0.323062,0.009475,0.043943,0.003910,0.020027,2.125832e-07,1.155557e-07,4.082262e-07,2.088343e-07,5.147071e-07,0.999786,1.225717e-07,0.000045,0.000168,2.945333e-07,0.031068,0.014489,0.224308,0.024551,0.064751,0.171082,0.038586,0.248392,0.027772,0.155002,0.392279,0.011169,0.887206,0.018322,0.039026,0.844656,0.410979,0.241009,0.187652,0.128182,0.145923,0.297234,0.557542,0.442458,0.986128,0.013872,0.000363,0.999637,8172.0,0.961783,0.276467,0.961783,0.039828,0.093496,5.5416,4.0746,1.0,0.955963,0.970942,4.0,1.0,0.960766,0.960766,3.0,0.0,0.0,0.0,15.0,1.0

In [ ]:
import joblib
import json

def save_cvae_artifact(
    path,
    model,
    prep,
    *,
    c_cols,
    y_cont_cols,
    y_bin_cols,
    z_dim,
    hidden
):
    os.makedirs(path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(path, "model.pt"))
    joblib.dump(prep, os.path.join(path, "prep.pkl"))

    meta = {
        "c_cols": c_cols,
        "y_cont_cols": y_cont_cols,
        "y_bin_cols": y_bin_cols,
        "z_dim": z_dim,
        "hidden": list(hidden),
        "model_type": "CVAE",
        "version": "v1",
    }
    with open(os.path.join(path, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)