In [2]:
import pandas as pd

In [3]:
import psycopg2

DB_URL = "postgres://postgres:baseball162162@localhost:5432/musicbrainz_db?sslmode=disable"

def get_pg_conn():
    """
    Returns a new Postgres connection.
    Caller is responsible for closing it.
    """
    return psycopg2.connect(DB_URL)

## Funcitons for Creating and Inserting into Database

In [4]:
def create_blocked_high_level_audio_features_table(conn):
    """
    Creates the blocked_high_level_audio_features table if it does not already exist.
    Stores PCA-compressed high-level audio features per MusicBrainz recording.
    """

    q = """
    DROP TABLE IF EXISTS blocked_high_level_audio_features;
    
    CREATE TABLE blocked_high_level_audio_features (
        recording_id INTEGER NOT NULL,
        recording_gid UUID NOT NULL,

        danceability DOUBLE PRECISION,
        gender_female DOUBLE PRECISION,
        timbre_bright DOUBLE PRECISION,
        tonal_atonal_atonal DOUBLE PRECISION,
        voice_instrumental_instrumental DOUBLE PRECISION,

        genre_dortmund_PC1 DOUBLE PRECISION,
        genre_dortmund_PC2 DOUBLE PRECISION,
        genre_dortmund_PC3 DOUBLE PRECISION,
        genre_dortmund_PC4 DOUBLE PRECISION,

        genre_electronic_PC1 DOUBLE PRECISION,
        genre_electronic_PC2 DOUBLE PRECISION,

        genre_rosamerica_PC1 DOUBLE PRECISION,
        genre_rosamerica_PC2 DOUBLE PRECISION,
        genre_rosamerica_PC3 DOUBLE PRECISION,
        genre_rosamerica_PC4 DOUBLE PRECISION,
        genre_rosamerica_PC5 DOUBLE PRECISION,
        genre_rosamerica_PC6 DOUBLE PRECISION,

        genre_tzanetakis_PC1 DOUBLE PRECISION,
        genre_tzanetakis_PC2 DOUBLE PRECISION,
        genre_tzanetakis_PC3 DOUBLE PRECISION,
        genre_tzanetakis_PC4 DOUBLE PRECISION,

        ismir04_rhythm_PC1 DOUBLE PRECISION,
        ismir04_rhythm_PC2 DOUBLE PRECISION,
        ismir04_rhythm_PC3 DOUBLE PRECISION,
        ismir04_rhythm_PC4 DOUBLE PRECISION,
        ismir04_rhythm_PC5 DOUBLE PRECISION,

        mood_PC1 DOUBLE PRECISION,
        mood_PC2 DOUBLE PRECISION,
        mood_PC3 DOUBLE PRECISION,
        mood_PC4 DOUBLE PRECISION,
        mood_PC5 DOUBLE PRECISION,
        mood_PC6 DOUBLE PRECISION,

        moods_mirex_PC1 DOUBLE PRECISION,
        moods_mirex_PC2 DOUBLE PRECISION,
        moods_mirex_PC3 DOUBLE PRECISION,
        moods_mirex_PC4 DOUBLE PRECISION,
        moods_mirex_PC5 DOUBLE PRECISION,

        CONSTRAINT blocked_high_level_audio_features_pk
            PRIMARY KEY (recording_id),

        CONSTRAINT blocked_high_level_audio_features_gid_unique
            UNIQUE (recording_gid),

        CONSTRAINT blocked_high_level_audio_features_recording_fk
            FOREIGN KEY (recording_id)
            REFERENCES recording(id)
            ON DELETE CASCADE,

        CONSTRAINT blocked_high_level_audio_features_recording_gid_fk
            FOREIGN KEY (recording_gid)
            REFERENCES recording(gid)
            ON DELETE CASCADE
    );
    """

    with conn.cursor() as cur:
        cur.execute(q)

    conn.commit()

In [5]:
from psycopg2.extras import execute_values


def insert_blocked_high_level_audio_features_from_df(conn, df, blocked_features):

    df = df.copy()

    # normalize
    df = df.drop(columns=["recording_id"], errors="ignore")
    df.columns = df.columns.str.lower().str.replace("-", "_", regex=False)

    if "recording_gid" not in df.columns:
        raise ValueError("recording_gid is required")

    # ensure recording_gid is NOT treated as a feature
    blocked_features = [c for c in blocked_features if c != "recording_gid"]

    # add missing feature columns as null
    for col in blocked_features:
        if col not in df.columns:
            df[col] = None

    # enforce column ordering for staging insert
    df = df[["recording_gid"] + blocked_features]

    values = [tuple(row) for row in df.itertuples(index=False)]

    # --------------------------------
    # staging table
    # --------------------------------
    create_staging = """
    CREATE TEMP TABLE stg_blocked_high_level_audio_features (
        recording_gid UUID NOT NULL
    ) ON COMMIT DROP;
    """

    # dynamically add columns for features
    alter_cols = [
        f'ALTER TABLE stg_blocked_high_level_audio_features '
        f'ADD COLUMN IF NOT EXISTS {c} DOUBLE PRECISION;'
        for c in blocked_features
    ]

    insert_stage = f"""
        INSERT INTO stg_blocked_high_level_audio_features (
            recording_gid,{",".join(blocked_features)}
        )
        VALUES %s
    """

    # --------------------------------
    # INSERT -> final table
    # --------------------------------
    insert_cols = ", ".join(
        ["recording_id", "recording_gid"] + blocked_features
    )

    select_cols = ", ".join(
        ["r.id AS recording_id", "s.recording_gid"] +
        [f"s.{c}" for c in blocked_features]
    )

    insert_final = f"""
    INSERT INTO blocked_high_level_audio_features (
        {insert_cols}
    )
    SELECT
        {select_cols}
    FROM stg_blocked_high_level_audio_features s
    JOIN recording r
      ON r.gid = s.recording_gid
    ON CONFLICT (recording_id) DO NOTHING;
    """

    # --------------------------------
    # execute
    # --------------------------------
    with conn.cursor() as cur:
        cur.execute(create_staging)

        for stmt in alter_cols:
            cur.execute(stmt)

        execute_values(cur, insert_stage, values, page_size=1000)
        cur.execute(insert_final)

    conn.commit()

## Create Principle Components From our High Level Data

#### Yep, removing the following
##### 1. Binary pairs:  ex/gender_male
##### 2. reducing each classifer block to their respective PCA components to eliminate colinearity
#####   2.1 genre_dortmund_ has 8 different classification projections, remove 1 and reduce the data to it's PCA. Repeat for all Classificaiton types

# Get all of the high_level recordings data
q = """
    SELECT * 
    FROM high_level_track_audio_features
"""

conn = get_pg_conn()
recordings = pd.read_sql_query(q, con=conn)
conn.close

## Steps 
→ raw AcousticBrainz JSON

→ feature extraction (dict → numeric columns)

→ schema alignment (fixed column order)

→ imputation (optional but recommended)

→ scaling (StandardScaler, incremental)

→ IncrementalPCA (partial_fit)

→ store PCA features (pc_1 … pc_k)

→ downstream models (logistic, CVAE, etc.)

In [6]:
# Separate numeric and non-numeric columns
# Modeling and PCA require numeric only, but dropping NA will remap
''' Get just the first few rows so that we can set all of the column data first & check the data '''

q = """
    SELECT * 
    FROM high_level_track_audio_features
    LIMIT 100
"""

conn = get_pg_conn()
recordings = pd.read_sql_query(q, con=conn)
conn.close

# ------------------------
# Just the column setting
# ------------------------
X = recordings.select_dtypes(include = "float").dropna()

numeric_cols = recordings.select_dtypes(include="float").columns.tolist()
non_numeric_cols = recordings.columns.difference(numeric_cols).tolist()

X = recordings[numeric_cols].dropna()
non_numeric_map = recordings.loc[X.index, non_numeric_cols].copy()

/tmp/ipykernel_23112/3281326014.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  recordings = pd.read_sql_query(q, con=conn)

In [7]:
pd.set_option('display.max_columns',None)
recordings

,recording_id,recording_gid,danceability,gender_female,gender_male,genre_dortmund_alternative,genre_dortmund_blues,genre_dortmund_electronic,genre_dortmund_folkcountry,genre_dortmund_funksoulrnb,genre_dortmund_jazz,genre_dortmund_pop,genre_dortmund_raphiphop,genre_dortmund_rock,genre_electronic_ambient,genre_electronic_dnb,genre_electronic_house,genre_electronic_techno,genre_electronic_trance,genre_rosamerica_cla,genre_rosamerica_dan,genre_rosamerica_hip,genre_rosamerica_jaz,genre_rosamerica_pop,genre_rosamerica_rhy,genre_rosamerica_roc,genre_rosamerica_spe,genre_tzanetakis_blu,genre_tzanetakis_cla,genre_tzanetakis_cou,genre_tzanetakis_dis,genre_tzanetakis_hip,genre_tzanetakis_jaz,genre_tzanetakis_met,genre_tzanetakis_pop,genre_tzanetakis_reg,genre_tzanetakis_roc,ismir04_rhythm_chachacha,ismir04_rhythm_jive,ismir04_rhythm_quickstep,ismir04_rhythm_rumba_american,ismir04_rhythm_rumba_international,ismir04_rhythm_rumba_misc,ismir04_rhythm_samba,ismir04_rhythm_tango,ismir04_rhythm_viennesewaltz,ismir04_rhythm_waltz,mood_acoustic,mood_aggressive,mood_electronic,mood_happy,mood_party,mood_relaxed,mood_sad,moods_mirex_cluster1,moods_mirex_cluster2,moods_mirex_cluster3,moods_mirex_cluster4,moods_mirex_cluster5,timbre_bright,timbre_dark,tonal_atonal_atonal,tonal_atonal_tonal,voice_instrumental_instrumental,voice_instrumental_voice
0,22007,0e11c0fd-a1da-4b88-a438-7ef55c5809ec,0.588381,0.723689,0.276311,3.049479e-08,3.517385e-08,0.999994,2.350741e-06,8.463293e-08,3.574956e-06,1.188261e-07,2.758425e-08,2.816739e-07,0.594397,0.010435,0.209968,0.020023,0.165177,0.056429,0.008282,0.021863,0.035198,0.445606,0.348569,0.065574,0.018478,0.056555,0.079166,0.079159,0.079158,0.065968,0.131944,0.079175,0.197943,0.098973,0.131957,None,0.010442,0.005996,0.012459,0.007263,0.007371,0.011816,0.596882,None,0.004705,0.182972,1.558052e-02,0.229635,0.102452,0.242396,0.793853,0.382577,0.064339,0.069062,0.383741,0.083837,0.399022,0.095759,0.904241,0.979121,2.087939e-02,0.182331,0.817669
1,22009,7fef22bd-76aa-4803-b56b-93a5d6e70662,0.660521,0.572842,0.427158,2.454308e-04,3.986965e-06,0.999673,2.405631e-05,3.418349e-07,1.085518e-05,1.735612e-06,8.564245e-08,4.031682e-05,0.635062,0.009534,0.148116,0.016951,0.190337,0.049024,0.021544,0.090095,0.104960,0.234919,0.379317,0.101442,0.018699,0.060564,0.033627,0.075655,0.060533,0.151351,0.302779,0.043215,0.060497,0.060502,0.151277,None,0.141765,0.033941,0.048417,0.039657,0.031882,0.047771,0.159273,None,0.020038,0.132453,1.025431e-01,0.333155,0.320952,0.454174,0.738320,0.356731,0.067106,0.068020,0.226084,0.058253,0.580537,0.907238,0.092762,0.238282,7.617185e-01,0.974387,0.025614
2,22012,71c0e054-b700-4fd2-a35b-95c7afc566cb,0.900021,0.707725,0.292275,6.504910e-02,1.602797e-02,0.846661,5.179366e-02,1.420159e-03,2.820769e-03,3.525711e-03,1.268555e-03,1.143280e-02,0.812620,0.005434,0.074116,0.007144,0.100685,0.326875,0.018928,0.039356,0.052348,0.171870,0.287400,0.077085,0.026138,0.065980,0.036651,0.109971,0.066037,0.110097,0.330444,0.066103,0.082600,0.066062,0.066055,None,0.090680,0.030573,0.039927,0.058391,0.034294,0.043401,0.244290,None,0.028436,0.728256,1.168093e-02,0.039353,0.253147,0.077503,0.941233,0.784938,0.101810,0.178213,0.404821,0.163250,0.151905,0.991651,0.008349,0.026941,9.730592e-01,0.004262,0.995738
3,22010,2d1201cf-59bb-4ffa-9f52-f5b3afa13346,0.964369,0.248086,0.751914,3.184711e-11,3.819828e-11,0.999999,3.182348e-08,1.647400e-08,3.432952e-07,1.561848e-08,1.559498e-08,1.185085e-07,0.797793,0.001054,0.054087,0.005712,0.141354,0.095582,0.003997,0.005574,0.028006,0.137816,0.709819,0.009465,0.009740,0.062661,0.034817,0.104476,0.078432,0.156924,0.313975,0.044817,0.062736,0.062736,0.078426,None,0.004935,0.000850,0.003364,0.001659,0.003885,0.002043,0.008247,None,0.001324,0.738541,6.969316e-02,0.445440,0.212858,0.035579,0.988763,0.422259,0.073824,0.059550,0.234088,0.040340,0.592198,0.556755,0.443245,0.449884,5.501158e-01,0.584680,0.415320
4,22005,96685213-a25c-4678-9a13-abd9ec81cf35,0.757807,0.614754,0.385246,2.113519e-02,4.137142e-03,0.962056,5.929591e-03,2.584509e-04,3.398424e-03,7.222621e-04,2.312433e-04,2.132163e-03,0.837813,0.009123,0.081379,0.020784,0.050901,0.036451,0.015602,0.130080,0.326542,0.080133,0.373972,0.013195,0.024024,0.069683,0.038708,0.087090,0.058059,0.174175,0.174175,0.049762,0.087085,0.087087,0.174177,None,0.006736,0.001570,0.033970,0.005782,0.004324,0.009526,0.912700,None,0.001866,0.270631,8.922327e-03,0.423497,0.055017,0.272155,0.966626,0.488107,0.077206,0.044455,0.227797,0.030656,0.619887,0.317574,0.682426,0.680931,3.190686e-01,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,615020,c8aeb5e9-2177-4604-aff2-238745c29eeb,0.973658,0.579839,0.420161,1.348973e-01,1.461560e-01,0.330970,2.273841e-01,1.420577e-02,4.206996e-02,1.787920e-02,9.278562e-03,7.715929e-02,0.915930,0.007133,0.056554,0.012520,0.007862,0.850728,0.003648,0.013106,0.023163,0.027840,0.063929,0.011083,0.006503,0.075685,0.034268,0.102809,0.078589,0.154233,0.308462,0.044060,0.061684,0.063100,0.077109,None,0.004633,0.009545,0.008025,0.017662,0.052882,0.016889,0.742483,None,0.031674,0.873064,2.869354e-02,0.445427,0.027984,0.114478,0.993783,0.346841,0.125716,0.361147,0.153995,0.274825,0.084316,0.003714,0.996286,0.999999,6.673101e-07,0.130491,0.869509
96,615003,a7dbe861-621c-420a-b622-60968a8e11da,1.000000,0.979872,0.020128,2.882523e-02,2.420826e-02,0.826228,3.150837e-02,5.120343e-03,2.815970e-02,1.256604e-02,6.498771e-03,3.688550e-02,0.213629,0.056942,0.617584,0.038151,0.073695,0.013677,0.075157,0.558325,0.045455,0.042846,0.187820,0.023018,0.053701,0.051525,0.034328,0.061783,0.102980,0.102998,0.308959,0.044102,0.061739,0.077184,0.154402,None,0.115886,0.007793,0.011214,0.013940,0.002701,0.032719,0.004920,None,0.001355,0.095590,9.999999e-01,0.979392,0.043688,0.000016,0.808817,0.223226,0.077223,0.044404,0.227748,0.030632,0.619994,0.033133,0.966867,0.995049,4.950546e-03,0.017379,0.982621
97,615005,a9648510-1b37-4c8d-813d-6265dacc4efb,1.000000,0.698584,0.301416,1.130770e-02,1.757488e-03,0.970547,4.681279e-03,3.324815e-04,7.549113e-03,1.335909e-03,1.677387e-04,2.321234e-03,0.656777,0.024546,0.234157,0.045214,0.039306,0.005486,0.082956,0.041724,0.120336,0.215716,0.503652,0.021404,0.008726,0.056707,0.079384,0.079382,0.099231,0.056708,0.132326,0.099255,0.198510,0.099251,0.099246,None,0.024671,0.011776,0.054394,0.477695,0.030542,0.067776,0.094195,None,0.005660,0.064061,3.000001e-14,0.911895,0.036785,0.000029,0.808817,0.684975,0.130274,0.303472,0.335347,0.106118,0.124789,0.002193,0.997807,0.737999,2.620007e-01,0.995724,0.004276
98,614999,604047fb-836f-475d-81aa-c9bc016b3984,0.973974,0.961972,0.038028,3.917708e-02,4.552698e-02,0.761589,7.712393e-02,4.782576e-03,4.134459e-02,5.237421e-03,1.215645e-03,2.400289e-02,0.953761,0.002680,0.029471,0.003794,0.010294,0.115327,0.005468,0.004186,0.620360,0.082551,0.143053,0.022746,0.006310,0.045578,0.063796,0.063784,0.063777,0.053145,0.159435,0.045555,0.106296,0.079726,0.318908,None,0.000560,0.003646,0.004881,0.003011,0.004910,0.002051,0.856124,None,0.025132,0.832014,1.533647e-06,0.823351,0.043194,0.005358,0.861765,0.730484,0.116157,0.154434,0.420375,0.285201,0.023833,0.352709,0.647291,0.305796,6.942044e-01,0.972137,0.027863
99,615014,043f03c3-c45c-49b9-ad27-36ae0b0a66fe,0.983358,0.975300,0.024700,2.003652e-01,1.810445e-01,0.042069,2.443887e-01,2.381241e-02,1.315809e-01,5.279107e-02,4.294801e-03,1.196535e-01,0.951505,0.009878,0.019682,0.005138,0.013797,0.922664,0.003066,0.001387,0.001686,0.007584,0.015873,0.047139,0.000602,0.062661,0.034817,0.104476,0.078432,0.156924,0.313975,0.044817,0.062736,0.062736,0.078426,None,0.028702,0.011911,0.004941,0.005816,0.009630,0.010641,0.063583,None,0.156693,0.189462,4.748712e-03,0.181534,0.841646,0.411726,0.846850,0.616353,0.142051,0.470848,0.071392,0.129079,0.186631,0.855696,0.144304,0.102721,8.972793e-01,0.970495,0.029505

In [8]:
from collections import defaultdict

def find_prefix_blocks(columns, min_block_size=2):
    """
    Groups columns by shared prefix (everything before last '_').

    Returns dict: {prefix: [col1, col2, ...]}
    """
    blocks = defaultdict(list)

    for col in columns:
        if "_" in col:
            prefix = "_".join(col.split("_")[:-1])
            blocks[prefix].append(col)

    return {
        k: v for k, v in blocks.items()
        if len(v) >= min_block_size
    }

In [9]:
genre_blocks = find_prefix_blocks(X.columns)
genre_blocks

{'gender': ['gender_female', 'gender_male'],
 'genre_dortmund': ['genre_dortmund_alternative',
  'genre_dortmund_blues',
  'genre_dortmund_electronic',
  'genre_dortmund_folkcountry',
  'genre_dortmund_funksoulrnb',
  'genre_dortmund_jazz',
  'genre_dortmund_pop',
  'genre_dortmund_raphiphop',
  'genre_dortmund_rock'],
 'genre_electronic': ['genre_electronic_ambient',
  'genre_electronic_dnb',
  'genre_electronic_house',
  'genre_electronic_techno',
  'genre_electronic_trance'],
 'genre_rosamerica': ['genre_rosamerica_cla',
  'genre_rosamerica_dan',
  'genre_rosamerica_hip',
  'genre_rosamerica_jaz',
  'genre_rosamerica_pop',
  'genre_rosamerica_rhy',
  'genre_rosamerica_roc',
  'genre_rosamerica_spe'],
 'genre_tzanetakis': ['genre_tzanetakis_blu',
  'genre_tzanetakis_cla',
  'genre_tzanetakis_cou',
  'genre_tzanetakis_dis',
  'genre_tzanetakis_hip',
  'genre_tzanetakis_jaz',
  'genre_tzanetakis_met',
  'genre_tzanetakis_pop',
  'genre_tzanetakis_reg',
  'genre_tzanetakis_roc'],
 'ismir04_rhythm': ['ismir04_rhythm_jive',
  'ismir04_rhythm_quickstep',
  'ismir04_rhythm_samba',
  'ismir04_rhythm_tango',
  'ismir04_rhythm_waltz'],
 'ismir04_rhythm_rumba': ['ismir04_rhythm_rumba_american',
  'ismir04_rhythm_rumba_international',
  'ismir04_rhythm_rumba_misc'],
 'mood': ['mood_acoustic',
  'mood_aggressive',
  'mood_electronic',
  'mood_happy',
  'mood_party',
  'mood_relaxed',
  'mood_sad'],
 'moods_mirex': ['moods_mirex_cluster1',
  'moods_mirex_cluster2',
  'moods_mirex_cluster3',
  'moods_mirex_cluster4',
  'moods_mirex_cluster5'],
 'timbre': ['timbre_bright', 'timbre_dark'],
 'tonal_atonal': ['tonal_atonal_atonal', 'tonal_atonal_tonal'],
 'voice_instrumental': ['voice_instrumental_instrumental',
  'voice_instrumental_voice']}

In [10]:
import numpy as np
import itertools

def find_complementary_pairs(
    X,
    corr_threshold=-0.95,
    sum_std_threshold=1e-3
):
    """
    Finds column pairs where:
    - correlation is strongly negative
    - row-wise sum is approximately constant

    Returns list of tuples: (col1, col2)
    """
    pairs = []

    corr = X.corr()

    for c1, c2 in itertools.combinations(X.columns, 2):
        if corr.loc[c1, c2] < corr_threshold:
            s = X[c1] + X[c2]
            if s.std() < sum_std_threshold:
                pairs.append((c1, c2))

    return pairs

In [11]:
complementary_pairs = find_complementary_pairs(X)
complementary_pairs

[('gender_female', 'gender_male'),
 ('timbre_bright', 'timbre_dark'),
 ('tonal_atonal_atonal', 'tonal_atonal_tonal'),
 ('voice_instrumental_instrumental', 'voice_instrumental_voice')]

In [12]:
def drop_complementary_columns(X, complementary_pairs):
    """
    Drops one column from each complementary pair.
    """
    to_drop = {pair[1] for pair in complementary_pairs}
    X_dropped = X.drop(columns=to_drop, errors="ignore")

    return X_dropped, to_drop

In [13]:
X_step1, dropped_complements = drop_complementary_columns(
    X, complementary_pairs
)

In [14]:
from sklearn.decomposition import IncrementalPCA

def incremental_pca_block(block_cols, query, engine, chunksize, n_components, out_writer):
    ipca = IncrementalPCA(n_components=n_components)

    # pass 1 — fit
    for chunk in pd.read_sql_query(query, engine, chunksize=chunksize):
        Xb = chunk[block_cols].astype("float32")
        ipca.partial_fit(Xb)

    # pass 2 — transform + write out
    for chunk in pd.read_sql_query(query, engine, chunksize=chunksize):
        Xb = chunk[block_cols].astype("float32")
        pcs = ipca.transform(Xb)
        out_writer(chunk.index, pcs)

    return ipca

In [15]:
from sklearn.decomposition import PCA

def pca_per_block(
    X,
    blocks,
    variance_threshold=0.95,
    min_components=1,
    max_components=None
):
    """
    Applies PCA separately to each feature block.
    Replaces block columns with PCA components.
    """
    X_out = X.copy()
    pca_models = {}

    for block_name, cols in blocks.items():
        cols = [c for c in cols if c in X_out.columns]
        if len(cols) < 2:
            continue

        X_block = X_out[cols]

        pca = PCA()
        pca.fit(X_block)

        cum_var = pca.explained_variance_ratio_.cumsum()
        n_comp = max(
            min_components,
            (cum_var >= variance_threshold).argmax() + 1
        )

        if max_components:
            n_comp = min(n_comp, max_components)

        pca = PCA(n_components=n_comp)
        pcs = pca.fit_transform(X_block)

        # add PCA columns
        pc_cols = [
            f"{block_name}_PC{i+1}" for i in range(n_comp)
        ]
        X_out[pc_cols] = pcs

        # drop original block
        X_out = X_out.drop(columns=cols)

        pca_models[block_name] = pca

    return X_out, pca_models

In [16]:
X_step2, pca_models = pca_per_block(
    X_step1,
    genre_blocks,
    variance_threshold=0.95
)

In [17]:
genre_blocks

{'gender': ['gender_female', 'gender_male'],
 'genre_dortmund': ['genre_dortmund_alternative',
  'genre_dortmund_blues',
  'genre_dortmund_electronic',
  'genre_dortmund_folkcountry',
  'genre_dortmund_funksoulrnb',
  'genre_dortmund_jazz',
  'genre_dortmund_pop',
  'genre_dortmund_raphiphop',
  'genre_dortmund_rock'],
 'genre_electronic': ['genre_electronic_ambient',
  'genre_electronic_dnb',
  'genre_electronic_house',
  'genre_electronic_techno',
  'genre_electronic_trance'],
 'genre_rosamerica': ['genre_rosamerica_cla',
  'genre_rosamerica_dan',
  'genre_rosamerica_hip',
  'genre_rosamerica_jaz',
  'genre_rosamerica_pop',
  'genre_rosamerica_rhy',
  'genre_rosamerica_roc',
  'genre_rosamerica_spe'],
 'genre_tzanetakis': ['genre_tzanetakis_blu',
  'genre_tzanetakis_cla',
  'genre_tzanetakis_cou',
  'genre_tzanetakis_dis',
  'genre_tzanetakis_hip',
  'genre_tzanetakis_jaz',
  'genre_tzanetakis_met',
  'genre_tzanetakis_pop',
  'genre_tzanetakis_reg',
  'genre_tzanetakis_roc'],
 'ismir04_rhythm': ['ismir04_rhythm_jive',
  'ismir04_rhythm_quickstep',
  'ismir04_rhythm_samba',
  'ismir04_rhythm_tango',
  'ismir04_rhythm_waltz'],
 'ismir04_rhythm_rumba': ['ismir04_rhythm_rumba_american',
  'ismir04_rhythm_rumba_international',
  'ismir04_rhythm_rumba_misc'],
 'mood': ['mood_acoustic',
  'mood_aggressive',
  'mood_electronic',
  'mood_happy',
  'mood_party',
  'mood_relaxed',
  'mood_sad'],
 'moods_mirex': ['moods_mirex_cluster1',
  'moods_mirex_cluster2',
  'moods_mirex_cluster3',
  'moods_mirex_cluster4',
  'moods_mirex_cluster5'],
 'timbre': ['timbre_bright', 'timbre_dark'],
 'tonal_atonal': ['tonal_atonal_atonal', 'tonal_atonal_tonal'],
 'voice_instrumental': ['voice_instrumental_instrumental',
  'voice_instrumental_voice']}

In [18]:
# Recombine numeric + non-numeric columns
X_with_metadata = pd.concat([X, non_numeric_map], axis=1)

In [19]:
X_with_metadata.head(2)

,danceability,gender_female,gender_male,genre_dortmund_alternative,genre_dortmund_blues,genre_dortmund_electronic,genre_dortmund_folkcountry,genre_dortmund_funksoulrnb,genre_dortmund_jazz,genre_dortmund_pop,genre_dortmund_raphiphop,genre_dortmund_rock,genre_electronic_ambient,genre_electronic_dnb,genre_electronic_house,genre_electronic_techno,genre_electronic_trance,genre_rosamerica_cla,genre_rosamerica_dan,genre_rosamerica_hip,genre_rosamerica_jaz,genre_rosamerica_pop,genre_rosamerica_rhy,genre_rosamerica_roc,genre_rosamerica_spe,genre_tzanetakis_blu,genre_tzanetakis_cla,genre_tzanetakis_cou,genre_tzanetakis_dis,genre_tzanetakis_hip,genre_tzanetakis_jaz,genre_tzanetakis_met,genre_tzanetakis_pop,genre_tzanetakis_reg,genre_tzanetakis_roc,ismir04_rhythm_jive,ismir04_rhythm_quickstep,ismir04_rhythm_rumba_american,ismir04_rhythm_rumba_international,ismir04_rhythm_rumba_misc,ismir04_rhythm_samba,ismir04_rhythm_tango,ismir04_rhythm_waltz,mood_acoustic,mood_aggressive,mood_electronic,mood_happy,mood_party,mood_relaxed,mood_sad,moods_mirex_cluster1,moods_mirex_cluster2,moods_mirex_cluster3,moods_mirex_cluster4,moods_mirex_cluster5,timbre_bright,timbre_dark,tonal_atonal_atonal,tonal_atonal_tonal,voice_instrumental_instrumental,voice_instrumental_voice,ismir04_rhythm_chachacha,ismir04_rhythm_viennesewaltz,recording_gid,recording_id
0,0.588381,0.723689,0.276311,3.049479e-08,3.517385e-08,0.999994,0.000002,8.463293e-08,0.000004,1.188261e-07,2.758425e-08,2.816739e-07,0.594397,0.010435,0.209968,0.020023,0.165177,0.056429,0.008282,0.021863,0.035198,0.445606,0.348569,0.065574,0.018478,0.056555,0.079166,0.079159,0.079158,0.065968,0.131944,0.079175,0.197943,0.098973,0.131957,0.010442,0.005996,0.012459,0.007263,0.007371,0.011816,0.596882,0.004705,0.182972,0.015581,0.229635,0.102452,0.242396,0.793853,0.382577,0.064339,0.069062,0.383741,0.083837,0.399022,0.095759,0.904241,0.979121,0.020879,0.182331,0.817669,None,None,0e11c0fd-a1da-4b88-a438-7ef55c5809ec,22007
1,0.660521,0.572842,0.427158,2.454308e-04,3.986965e-06,0.999673,0.000024,3.418349e-07,0.000011,1.735612e-06,8.564245e-08,4.031682e-05,0.635062,0.009534,0.148116,0.016951,0.190337,0.049024,0.021544,0.090095,0.104960,0.234919,0.379317,0.101442,0.018699,0.060564,0.033627,0.075655,0.060533,0.151351,0.302779,0.043215,0.060497,0.060502,0.151277,0.141765,0.033941,0.048417,0.039657,0.031882,0.047771,0.159273,0.020038,0.132453,0.102543,0.333155,0.320952,0.454174,0.738320,0.356731,0.067106,0.068020,0.226084,0.058253,0.580537,0.907238,0.092762,0.238282,0.761719,0.974387,0.025614,None,None,7fef22bd-76aa-4803-b56b-93a5d6e70662,22009

In [20]:
conn.close()
conn = get_pg_conn()

In [21]:
BLOCKED_FEATURE_COLUMNS = [
    "recording_gid",

    "danceability",
    "gender_female",
    "timbre_bright",
    "tonal_atonal_atonal",
    "voice_instrumental_instrumental",

    "genre_dortmund_pc1",
    "genre_dortmund_pc2",
    "genre_dortmund_pc3",
    "genre_dortmund_pc4",

    "genre_electronic_pc1",
    "genre_electronic_pc2",

    "genre_rosamerica_pc1",
    "genre_rosamerica_pc2",
    "genre_rosamerica_pc3",
    "genre_rosamerica_pc4",
    "genre_rosamerica_pc5",
    "genre_rosamerica_pc6",

    "genre_tzanetakis_pc1",
    "genre_tzanetakis_pc2",
    "genre_tzanetakis_pc3",
    "genre_tzanetakis_pc4",

    "ismir04_rhythm_pc1",
    "ismir04_rhythm_pc2",
    "ismir04_rhythm_pc3",
    # "ismir04_rhythm_pc4",
    # "ismir04_rhythm_pc5",

    "mood_pc1",
    "mood_pc2",
    "mood_pc3",
    "mood_pc4",
    "mood_pc5",
    "mood_pc6",

    "moods_mirex_pc1",
    "moods_mirex_pc2",
    "moods_mirex_pc3"
]

## Do the Incremental PCA
- We have created the table, schema, and the features above. 
- Now implement

In [22]:
import pandas as pd
from sqlalchemy import create_engine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import IncrementalPCA

# engine = create_engine(
#     "postgres://postgres:baseball162162@localhost:5432/musicbrainz_db?sslmode=disable"
# )

query = """
SELECT *
FROM high_level_track_audio_features;
"""

N_COMPONENTS = 32
BATCH_SIZE = 30000
PCA_VERSION = "feature_engineering/features/highlevel_pca_v1"
BLOCKED_PCA_TABLE_NAME = "blocked_high_level_audio_features"
ARTIFACT_PATH = f"{PCA_VERSION}.joblib"
VAR_THRESHOLD = 0.95 # Threshold of amount of variance a PC needs to be included

##### Initialize the block-PCA model

In [23]:
def init_block_models(blocks, max_components=None):
    models = {}

    for block, cols in blocks.items():
        if len(cols) < 2:
            continue

        k = min(len(cols), max_components or len(cols))

        models[block] = {
            "cols": cols,
            "scaler": StandardScaler(),
            "ipca": IncrementalPCA(
                n_components=k,
                batch_size=BATCH_SIZE
            )
        }

    return models

In [24]:
def stream_feature_batches(conn, feature_columns, batch_size=BATCH_SIZE):
    offset = 0

    while True:
        query = f"""
        SELECT
            recording_gid,
            {",".join(feature_columns)}
        FROM high_level_track_audio_features
        ORDER BY recording_gid
        LIMIT {batch_size}
        OFFSET {offset}
        """

        df = pd.read_sql(query, conn)
        if df.empty:
            break

        yield df
        offset += batch_size
        
        
def get_total_rows(conn):
    with conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM high_level_track_audio_features")
        return cur.fetchone()[0]

In [25]:
ALL_FEATURE_COLS = [
    col
    for cols in genre_blocks.values()
    for col in cols
]

In [26]:
from tqdm import tqdm
import numpy as np
import gc

# ----------------------------------
# Init
# ----------------------------------
block_models = init_block_models(genre_blocks)

conn.close()
conn = get_pg_conn()

total_rows = get_total_rows(conn)
total_batches = (total_rows + BATCH_SIZE - 1) // BATCH_SIZE

# ----------------------------------
# PASS 1 — fit scalers
# ----------------------------------
for df in tqdm(
    stream_feature_batches(conn, ALL_FEATURE_COLS, batch_size=BATCH_SIZE),
    total=total_batches,
    desc="PASS 1: fitting scalers",
):
    for block, m in block_models.items():
        cols = m["cols"]              # already validated
        X = df[cols].to_numpy(dtype=np.float32, copy=False)
        np.nan_to_num(X, copy=False)
        m["scaler"].partial_fit(X)

    # explicit cleanup
    del df
    gc.collect()

PASS 1: fitting scalers:   0%|          | 0/306 [00:00<?, ?it/s]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   0%|          | 1/306 [00:56<4:44:47, 56.02s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   1%|          | 2/306 [02:05<5:23:14, 63.80s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   1%|          | 3/306 [03:05<5:14:20, 62.25s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   1%|▏         | 4/306 [04:04<5:05:55, 60.78s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   2%|▏         | 5/306 [05:07<5:09:00, 61.60s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   2%|▏         | 6/306 [06:06<5:03:14, 60.65s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   2%|▏         | 7/306 [07:10<5:08:16, 61.86s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   3%|▎         | 8/306 [08:15<5:12:14, 62.87s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   3%|▎         | 9/306 [09:24<5:20:11, 64.69s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   3%|▎         | 10/306 [10:24<5:12:30, 63.35s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   4%|▎         | 11/306 [11:29<5:13:35, 63.78s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   4%|▍         | 12/306 [12:36<5:17:40, 64.83s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   4%|▍         | 13/306 [13:36<5:09:30, 63.38s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   5%|▍         | 14/306 [14:35<5:02:38, 62.19s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   5%|▍         | 15/306 [15:37<5:01:12, 62.10s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   5%|▌         | 16/306 [16:42<5:04:21, 62.97s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   6%|▌         | 17/306 [17:42<4:58:59, 62.08s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   6%|▌         | 18/306 [18:45<4:59:06, 62.31s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   6%|▌         | 19/306 [19:42<4:50:19, 60.69s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   7%|▋         | 20/306 [20:41<4:46:05, 60.02s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   7%|▋         | 21/306 [21:38<4:41:08, 59.19s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   7%|▋         | 22/306 [22:35<4:36:51, 58.49s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   8%|▊         | 23/306 [23:31<4:32:54, 57.86s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   8%|▊         | 24/306 [24:29<4:31:44, 57.82s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   8%|▊         | 25/306 [25:27<4:31:26, 57.96s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   8%|▊         | 26/306 [26:26<4:31:33, 58.19s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   9%|▉         | 27/306 [27:30<4:39:04, 60.02s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   9%|▉         | 28/306 [28:31<4:39:55, 60.41s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:   9%|▉         | 29/306 [29:33<4:40:47, 60.82s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  10%|▉         | 30/306 [30:31<4:36:02, 60.01s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  10%|█         | 31/306 [31:32<4:36:26, 60.31s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  10%|█         | 32/306 [32:43<4:49:37, 63.42s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  11%|█         | 33/306 [33:50<4:53:46, 64.57s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  11%|█         | 34/306 [34:53<4:49:46, 63.92s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  11%|█▏        | 35/306 [35:57<4:49:45, 64.15s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  12%|█▏        | 36/306 [36:56<4:40:41, 62.38s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  12%|█▏        | 37/306 [37:57<4:38:48, 62.19s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  12%|█▏        | 38/306 [38:56<4:33:36, 61.25s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  13%|█▎        | 39/306 [39:57<4:31:28, 61.01s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  13%|█▎        | 40/306 [40:54<4:25:57, 59.99s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  13%|█▎        | 41/306 [41:51<4:20:12, 58.91s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  14%|█▎        | 42/306 [42:50<4:19:23, 58.95s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  14%|█▍        | 43/306 [43:53<4:23:50, 60.19s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  14%|█▍        | 44/306 [44:51<4:19:50, 59.50s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  15%|█▍        | 45/306 [45:50<4:18:41, 59.47s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  15%|█▌        | 46/306 [46:54<4:22:50, 60.66s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  15%|█▌        | 47/306 [48:01<4:29:50, 62.51s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  16%|█▌        | 48/306 [49:07<4:34:30, 63.84s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  16%|█▌        | 49/306 [50:10<4:32:21, 63.58s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  16%|█▋        | 50/306 [51:07<4:22:13, 61.46s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  17%|█▋        | 51/306 [52:05<4:16:34, 60.37s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  17%|█▋        | 52/306 [53:03<4:12:34, 59.66s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  17%|█▋        | 53/306 [54:05<4:15:12, 60.52s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  18%|█▊        | 54/306 [55:07<4:15:39, 60.87s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  18%|█▊        | 55/306 [56:10<4:16:47, 61.38s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 1: fitting scalers:  18%|█▊        | 56/306 [57:07<4:10:49, 60.20s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [27]:
scaler = StandardScaler()
ipca = IncrementalPCA(
    n_components=N_COMPONENTS,
    batch_size=BATCH_SIZE
)

In [28]:
from tqdm import tqdm
import numpy as np
import gc

# ----------------------------------
# PASS 2 — fit IncrementalPCA
# ----------------------------------
for df in tqdm(
    stream_feature_batches(conn, ALL_FEATURE_COLS, batch_size=BATCH_SIZE),
    total=total_batches,
    desc="PASS 2: fitting IncrementalPCA",
):
    for block, m in block_models.items():
        cols = m["cols"]   # assume schema validated once earlier

        X = df[cols].to_numpy(dtype=np.float32, copy=False)
        np.nan_to_num(X, copy=False)

        Xs = m["scaler"].transform(X)
        m["ipca"].partial_fit(Xs)

    # cleanup once per batch
    del df
    del X
    del Xs
    gc.collect()

PASS 2: fitting IncrementalPCA:   0%|          | 0/306 [00:00<?, ?it/s]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   0%|          | 1/306 [01:00<5:09:52, 60.96s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   1%|          | 2/306 [01:59<5:01:04, 59.42s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   1%|          | 3/306 [02:59<5:00:45, 59.56s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   1%|▏         | 4/306 [03:56<4:54:42, 58.55s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   2%|▏         | 5/306 [04:59<5:03:16, 60.45s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   2%|▏         | 6/306 [05:59<5:01:34, 60.31s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   2%|▏         | 7/306 [06:58<4:56:59, 59.60s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   3%|▎         | 8/306 [08:09<5:14:06, 63.24s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   3%|▎         | 9/306 [09:10<5:10:55, 62.81s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   3%|▎         | 10/306 [10:15<5:12:53, 63.42s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   4%|▎         | 11/306 [11:13<5:03:02, 61.63s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   4%|▍         | 12/306 [12:18<5:07:14, 62.70s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   4%|▍         | 13/306 [13:16<4:58:59, 61.23s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   5%|▍         | 14/306 [14:14<4:53:51, 60.38s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   5%|▍         | 15/306 [15:14<4:51:57, 60.20s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   5%|▌         | 16/306 [16:19<4:57:33, 61.56s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   6%|▌         | 17/306 [17:16<4:50:56, 60.40s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   6%|▌         | 18/306 [18:16<4:48:44, 60.16s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   6%|▌         | 19/306 [19:15<4:46:04, 59.81s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   7%|▋         | 20/306 [20:24<4:57:53, 62.49s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   7%|▋         | 21/306 [21:23<4:52:12, 61.52s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   7%|▋         | 22/306 [22:23<4:48:27, 60.94s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   8%|▊         | 23/306 [23:27<4:51:44, 61.85s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   8%|▊         | 24/306 [24:31<4:54:58, 62.76s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   8%|▊         | 25/306 [25:32<4:50:34, 62.04s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   8%|▊         | 26/306 [26:31<4:45:45, 61.23s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   9%|▉         | 27/306 [27:29<4:40:30, 60.32s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   9%|▉         | 28/306 [28:28<4:37:08, 59.81s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:   9%|▉         | 29/306 [29:26<4:33:53, 59.33s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  10%|▉         | 30/306 [30:30<4:39:21, 60.73s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  10%|█         | 31/306 [31:33<4:40:33, 61.21s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  10%|█         | 32/306 [34:55<7:53:05, 103.60s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  11%|█         | 33/306 [38:09<9:54:27, 130.65s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  11%|█         | 34/306 [39:10<8:18:15, 109.91s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  11%|█▏        | 35/306 [40:11<7:09:07, 95.01s/it] /tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  12%|█▏        | 36/306 [41:27<6:43:09, 89.59s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  12%|█▏        | 37/306 [42:35<6:12:09, 83.01s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  12%|█▏        | 38/306 [43:35<5:40:24, 76.21s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  13%|█▎        | 39/306 [44:47<5:33:26, 74.93s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  13%|█▎        | 40/306 [45:45<5:09:44, 69.87s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  13%|█▎        | 41/306 [46:49<4:59:33, 67.83s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  14%|█▎        | 42/306 [47:57<4:58:46, 67.90s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  14%|█▍        | 43/306 [48:59<4:49:55, 66.14s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  14%|█▍        | 44/306 [50:05<4:49:34, 66.31s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  15%|█▍        | 45/306 [51:11<4:47:07, 66.01s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  15%|█▌        | 46/306 [52:27<4:58:48, 68.95s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  15%|█▌        | 47/306 [53:25<4:44:14, 65.85s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  16%|█▌        | 48/306 [54:23<4:33:17, 63.56s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  16%|█▌        | 49/306 [55:20<4:23:19, 61.47s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  16%|█▋        | 50/306 [56:17<4:16:24, 60.09s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  17%|█▋        | 51/306 [57:24<4:25:02, 62.36s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  17%|█▋        | 52/306 [58:23<4:19:21, 61.27s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  17%|█▋        | 53/306 [59:27<4:21:47, 62.08s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  18%|█▊        | 54/306 [1:00:26<4:16:28, 61.07s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
PASS 2: fitting IncrementalPCA:  18%|█▊        | 55/306 [1:01:30<4:19:36, 62.06s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [29]:
for block, m in block_models.items():
    cum_var = m["ipca"].explained_variance_ratio_.cumsum()
    k = max(1, np.searchsorted(cum_var, VAR_THRESHOLD) + 1)

    m["keep_components"] = k

In [32]:
block_models

{'gender': {'cols': ['gender_female', 'gender_male'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=2),
  'keep_components': 1},
 'genre_dortmund': {'cols': ['genre_dortmund_alternative',
   'genre_dortmund_blues',
   'genre_dortmund_electronic',
   'genre_dortmund_folkcountry',
   'genre_dortmund_funksoulrnb',
   'genre_dortmund_jazz',
   'genre_dortmund_pop',
   'genre_dortmund_raphiphop',
   'genre_dortmund_rock'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=9),
  'keep_components': np.int64(7)},
 'genre_electronic': {'cols': ['genre_electronic_ambient',
   'genre_electronic_dnb',
   'genre_electronic_house',
   'genre_electronic_techno',
   'genre_electronic_trance'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=5),
  'keep_components': np.int64(4)},
 'genre_rosamerica': {'cols': ['genre_rosamerica_cla',
   'genre_rosamerica_dan',
   'genre_rosamerica_hip',
   'genre_rosamerica_jaz',
   'genre_rosamerica_pop',
   'genre_rosamerica_rhy',
   'genre_rosamerica_roc',
   'genre_rosamerica_spe'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=8),
  'keep_components': np.int64(7)},
 'genre_tzanetakis': {'cols': ['genre_tzanetakis_blu',
   'genre_tzanetakis_cla',
   'genre_tzanetakis_cou',
   'genre_tzanetakis_dis',
   'genre_tzanetakis_hip',
   'genre_tzanetakis_jaz',
   'genre_tzanetakis_met',
   'genre_tzanetakis_pop',
   'genre_tzanetakis_reg',
   'genre_tzanetakis_roc'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=10),
  'keep_components': np.int64(8)},
 'ismir04_rhythm': {'cols': ['ismir04_rhythm_jive',
   'ismir04_rhythm_quickstep',
   'ismir04_rhythm_samba',
   'ismir04_rhythm_tango',
   'ismir04_rhythm_waltz'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=5),
  'keep_components': np.int64(5)},
 'ismir04_rhythm_rumba': {'cols': ['ismir04_rhythm_rumba_american',
   'ismir04_rhythm_rumba_international',
   'ismir04_rhythm_rumba_misc'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=3),
  'keep_components': np.int64(3)},
 'mood': {'cols': ['mood_acoustic',
   'mood_aggressive',
   'mood_electronic',
   'mood_happy',
   'mood_party',
   'mood_relaxed',
   'mood_sad'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=7),
  'keep_components': np.int64(6)},
 'moods_mirex': {'cols': ['moods_mirex_cluster1',
   'moods_mirex_cluster2',
   'moods_mirex_cluster3',
   'moods_mirex_cluster4',
   'moods_mirex_cluster5'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=5),
  'keep_components': np.int64(4)},
 'timbre': {'cols': ['timbre_bright', 'timbre_dark'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=2),
  'keep_components': 1},
 'tonal_atonal': {'cols': ['tonal_atonal_atonal', 'tonal_atonal_tonal'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=2),
  'keep_components': 1},
 'voice_instrumental': {'cols': ['voice_instrumental_instrumental',
   'voice_instrumental_voice'],
  'scaler': StandardScaler(),
  'ipca': IncrementalPCA(batch_size=30000, n_components=2),
  'keep_components': 1}}

In [30]:
X = df.select_dtypes(include = "float").dropna()

numeric_cols = df.select_dtypes(include="float").columns.tolist()
non_numeric_cols = df.columns.difference(numeric_cols).tolist()

X = df[numeric_cols].dropna()
non_numeric_map = df.loc[X.index, non_numeric_cols].copy()
X_with_metadata = pd.concat([X, non_numeric_map], axis=1)

NameError: name 'df' is not defined

In [33]:
for block, m in block_models.items():
    cum_var = m["ipca"].explained_variance_ratio_.cumsum()
    k = max(1, np.searchsorted(cum_var, VAR_THRESHOLD) + 1)

    m["keep_components"] = k

In [34]:
import joblib

joblib.dump(
    {
        block: {
            "cols": m["cols"],
            "scaler": m["scaler"],
            "ipca": m["ipca"],
            "keep_components": m["keep_components"],
        }
        for block, m in block_models.items()
    },
    f"{PCA_VERSION}.joblib"
)

['feature_engineering/features/highlevel_pca_v1.joblib']

In [35]:
def transform_blocks(df, block_models):
    out = df[["recording_gid"]].copy()

    for block, m in block_models.items():
        cols = [c for c in m["cols"] if c in df.columns]
        X = df[cols].to_numpy(dtype=np.float32)
        X = np.nan_to_num(X)

        Xs = m["scaler"].transform(X)
        Xp = m["ipca"].transform(Xs)[:, : m["keep_components"]]

        for i in range(Xp.shape[1]):
            out[f"{block}_pc{i+1}"] = Xp[:, i]

    return out

In [36]:
def get_pca_columns(block_models):
    cols = []
    for block, m in block_models.items():
        k = m["keep_components"]
        for i in range(k):
            cols.append(f"{block}_pc{i+1}")
    return cols

In [37]:
PCA_COLS = get_pca_columns(block_models)

In [38]:
DROP_SQL = f"""
DROP TABLE IF EXISTS {BLOCKED_PCA_TABLE_NAME} ;
"""

CREATE_SQL = f"""
CREATE TABLE {BLOCKED_PCA_TABLE_NAME}  (
    recording_gid UUID NOT NULL,
    pca_version TEXT NOT NULL,
    {",".join([f"{c} REAL" for c in PCA_COLS])},
    PRIMARY KEY (recording_gid, pca_version)
);
"""

In [39]:
with conn.cursor() as cur:
    cur.execute(DROP_SQL)
    cur.execute(CREATE_SQL)

conn.commit()

In [51]:
len(PCA_COLS)

48

In [47]:
columns = [
    "recording_gid",
    "pca_version",
    "gender_pc1",
    "genre_dortmund_pc1",
    "genre_dortmund_pc2",
    "genre_dortmund_pc3",
    "genre_dortmund_pc4",
    "genre_dortmund_pc5",
    "genre_dortmund_pc6",
    "genre_dortmund_pc7",
    "genre_electronic_pc1",
    "genre_electronic_pc2",
    "genre_electronic_pc3",
    "genre_electronic_pc4",
    "genre_rosamerica_pc1",
    "genre_rosamerica_pc2",
    "genre_rosamerica_pc3",
    "genre_rosamerica_pc4",
    "genre_rosamerica_pc5",
    "genre_rosamerica_pc6",
    "genre_rosamerica_pc7",
    "genre_tzanetakis_pc1",
    "genre_tzanetakis_pc2",
    "genre_tzanetakis_pc3",
    "genre_tzanetakis_pc4",
    "genre_tzanetakis_pc5",
    "genre_tzanetakis_pc6",
    "genre_tzanetakis_pc7",
    "genre_tzanetakis_pc8",
    "ismir04_rhythm_pc1",
    "ismir04_rhythm_pc2",
    "ismir04_rhythm_pc3",
    "ismir04_rhythm_pc4",
    "ismir04_rhythm_pc5",
    "ismir04_rhythm_rumba_pc1",
    "ismir04_rhythm_rumba_pc2",
    "ismir04_rhythm_rumba_pc3",
    "mood_pc1",
    "mood_pc2",
    "mood_pc3",
    "mood_pc4",
    "mood_pc5",
    "mood_pc6",
    "moods_mirex_pc1",
    "moods_mirex_pc2",
    "moods_mirex_pc3",
    "moods_mirex_pc4",
    "timbre_pc1",
    "tonal_atonal_pc1",
    "voice_instrumental_pc1",
]

In [50]:
len(columns),len(df_pca.columns)

(50, 50)

In [48]:
[c for c in df_pca.columns if c not in columns]

[]

In [54]:
from psycopg2.extras import execute_values

INSERT_SQL = f"""
INSERT INTO {BLOCKED_PCA_TABLE_NAME} (
    recording_gid,
    pca_version,
    {",".join(PCA_COLS)}
)
VALUES %s
ON CONFLICT (recording_gid, pca_version)
DO NOTHING
"""

conn.close()
conn = get_pg_conn()
with conn.cursor() as cur:
    for df in tqdm(stream_feature_batches(conn,ALL_FEATURE_COLS)):
        df_pca = transform_blocks(df, block_models)

        df_pca.insert(1, "pca_version", PCA_VERSION)

        rows = [
            tuple(row)
            for row in df_pca.itertuples(index=False, name=None)
        ]

        execute_values(
            cur,
            INSERT_SQL,
            rows,
            page_size=1000
        )

conn.commit()

0it [00:00, ?it/s]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
1it [00:56, 56.58s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
2it [02:11, 67.07s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
3it [03:35, 75.05s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
4it [04:56, 77.30s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
5it [05:54, 70.41s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
6it [07:08, 71.51s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
7it [08:08, 67.76s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
8it [09:13, 66.90s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
9it [10:30, 70.08s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
10it [11:44, 71.47s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
11it [12:57, 71.86s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
12it [14:05, 70.52s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
13it [15:04, 67.30s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
14it [16:08, 66.20s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
15it [17:05, 63.45s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
16it [18:14, 64.93s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
17it [19:22, 65.88s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
18it [20:23, 64.60s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
19it [21:30, 65.15s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
20it [22:31, 63.85s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
21it [23:20, 59.49s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
22it [24:26, 61.54s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
23it [25:23, 60.16s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
24it [26:30, 62.24s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
25it [27:39, 64.33s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
26it [28:43, 64.12s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
27it [29:46, 63.72s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
28it [30:37, 60.05s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
29it [31:37, 59.88s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
30it [32:31, 58.07s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
31it [33:30, 58.43s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
32it [34:33, 59.86s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
33it [35:36, 60.62s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
34it [36:40, 61.83s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
35it [37:36, 60.16s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
36it [38:44, 62.52s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
37it [39:56, 65.13s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
38it [41:11, 68.12s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
39it [42:17, 67.55s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
40it [43:29, 68.87s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
41it [44:24, 64.67s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
42it [45:44, 69.29s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
43it [47:07, 73.57s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
44it [48:23, 74.26s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
45it [49:47, 77.19s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
46it [51:13, 79.77s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
47it [52:28, 78.34s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
48it [53:32, 73.91s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
49it [54:44, 73.52s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
50it [55:55, 72.68s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
51it [57:06, 72.02s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
52it [58:15, 71.32s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
53it [59:23, 70.25s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
54it [1:00:29, 69.03s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
55it [1:01:38, 68.91s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
56it [1:02:50, 70.01s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
57it [1:04:00, 69.91s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
58it [1:05:11, 70.33s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
59it [1:06:18, 69.12s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
60it [1:07:31, 70.32s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
61it [1:08:44, 71.23s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
62it [1:09:49, 69.24s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
63it [1:11:03, 70.89s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
64it [1:12:14, 70.76s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
65it [1:13:11, 66.61s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
66it [1:14:06, 63.09s/it]/tmp/ipykernel_23112/4252659801.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [55]:
conn.close()

In [ ]:
conn.close()
conn = get_pg_conn()
create_blocked_high_level_audio_features_table(conn)
insert_blocked_high_level_audio_features_from_df(conn,X_with_metadata,BLOCKED_FEATURE_COLUMNS)
conn.close()